// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfRealTimeCollector;

//
// IDL:iris.edu/Fissures/IfRealTimeCollector/RealTimeCollector:1.0
//
/**
 * The real time collector is an interface to accepts raw data from
 * data acquisition system. Implementation of this interface would
 * act as either store and forward proxies or seismogram creation
 * system.
 * Seismogram creation implementation would connect to
 * one or more Seismogram factories and create new seismogram then
 * append data to them. These implementation would have the
 * knowledge of how to partition raw data into seperate seismograms
 **/

public interface RealTimeCollector extends RealTimeCollectorOperations,
                                           org.omg.CORBA.Object,
                                           org.omg.CORBA.portable.IDLEntity
{
}
