// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfEvent;

//
// IDL:iris.edu/Fissures/IfEvent/Event:1.0
//
public abstract class EventPOA
    extends org.omg.PortableServer.Servant
    implements org.omg.CORBA.portable.InvokeHandler,
               EventOperations
{
    static final String[] _ob_ids_ =
    {
        "IDL:iris.edu/Fissures/IfEvent/Event:1.0",
        "IDL:iris.edu/Fissures/IfEvent/EventAccess:1.0",
        "IDL:iris.edu/Fissures/AuditSystemAccess:1.0",
        "IDL:iris.edu/Fissures/IfEvent/EventMgr:1.0",
        "IDL:iris.edu/Fissures/IfEvent/EventDC:1.0"
    };

    public Event
    _this()
    {
        return EventHelper.narrow(super._this_object());
    }

    public Event
    _this(org.omg.CORBA.ORB orb)
    {
        return EventHelper.narrow(super._this_object(orb));
    }

    public String[]
    _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId)
    {
        return _ob_ids_;
    }

    public org.omg.CORBA.portable.OutputStream
    _invoke(String opName,
            org.omg.CORBA.portable.InputStream in,
            org.omg.CORBA.portable.ResponseHandler handler)
    {
        final String[] _ob_names =
        {
            "_get_a_channel_finder",
            "_get_a_factory",
            "_get_a_finder",
            "_get_a_writeable",
            "_get_parm_svc",
            "add_locators",
            "add_magnitude",
            "add_origin",
            "delete_origin",
            "destroy",
            "get_attributes",
            "get_audit_trail",
            "get_audit_trail_for_origin",
            "get_locators",
            "get_origin",
            "get_origins",
            "get_preferred_origin",
            "set_preferred_origin",
            "update_region"
        };

        int _ob_left = 0;
        int _ob_right = _ob_names.length;
        int _ob_index = -1;

        while(_ob_left < _ob_right)
        {
            int _ob_m = (_ob_left + _ob_right) / 2;
            int _ob_res = _ob_names[_ob_m].compareTo(opName);
            if(_ob_res == 0)
            {
                _ob_index = _ob_m;
                break;
            }
            else if(_ob_res > 0)
                _ob_right = _ob_m;
            else
                _ob_left = _ob_m + 1;
        }

        switch(_ob_index)
        {
        case 0: // _get_a_channel_finder
            return _OB_att_get_a_channel_finder(in, handler);

        case 1: // _get_a_factory
            return _OB_att_get_a_factory(in, handler);

        case 2: // _get_a_finder
            return _OB_att_get_a_finder(in, handler);

        case 3: // _get_a_writeable
            return _OB_att_get_a_writeable(in, handler);

        case 4: // _get_parm_svc
            return _OB_att_get_parm_svc(in, handler);

        case 5: // add_locators
            return _OB_op_add_locators(in, handler);

        case 6: // add_magnitude
            return _OB_op_add_magnitude(in, handler);

        case 7: // add_origin
            return _OB_op_add_origin(in, handler);

        case 8: // delete_origin
            return _OB_op_delete_origin(in, handler);

        case 9: // destroy
            return _OB_op_destroy(in, handler);

        case 10: // get_attributes
            return _OB_op_get_attributes(in, handler);

        case 11: // get_audit_trail
            return _OB_op_get_audit_trail(in, handler);

        case 12: // get_audit_trail_for_origin
            return _OB_op_get_audit_trail_for_origin(in, handler);

        case 13: // get_locators
            return _OB_op_get_locators(in, handler);

        case 14: // get_origin
            return _OB_op_get_origin(in, handler);

        case 15: // get_origins
            return _OB_op_get_origins(in, handler);

        case 16: // get_preferred_origin
            return _OB_op_get_preferred_origin(in, handler);

        case 17: // set_preferred_origin
            return _OB_op_set_preferred_origin(in, handler);

        case 18: // update_region
            return _OB_op_update_region(in, handler);
        }

        throw new org.omg.CORBA.BAD_OPERATION();
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_att_get_a_channel_finder(org.omg.CORBA.portable.InputStream in,
                                 org.omg.CORBA.portable.ResponseHandler handler)
    {
        EventChannelFinder _ob_r = a_channel_finder();
        org.omg.CORBA.portable.OutputStream out = handler.createReply();
        EventChannelFinderHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_att_get_a_factory(org.omg.CORBA.portable.InputStream in,
                          org.omg.CORBA.portable.ResponseHandler handler)
    {
        EventFactory _ob_r = a_factory();
        org.omg.CORBA.portable.OutputStream out = handler.createReply();
        EventFactoryHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_att_get_a_finder(org.omg.CORBA.portable.InputStream in,
                         org.omg.CORBA.portable.ResponseHandler handler)
    {
        EventFinder _ob_r = a_finder();
        org.omg.CORBA.portable.OutputStream out = handler.createReply();
        EventFinderHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_att_get_a_writeable(org.omg.CORBA.portable.InputStream in,
                            org.omg.CORBA.portable.ResponseHandler handler)
    {
        Event _ob_r = a_writeable();
        org.omg.CORBA.portable.OutputStream out = handler.createReply();
        EventHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_att_get_parm_svc(org.omg.CORBA.portable.InputStream in,
                         org.omg.CORBA.portable.ResponseHandler handler)
    {
        edu.iris.Fissures.IfParameterMgr.ParameterComponent _ob_r = parm_svc();
        org.omg.CORBA.portable.OutputStream out = handler.createReply();
        edu.iris.Fissures.IfParameterMgr.ParameterComponentHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_add_locators(org.omg.CORBA.portable.InputStream in,
                        org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            String _ob_a0 = OriginIdHelper.read(in);
            Locator[] _ob_a1 = LocatorSeqHelper.read(in);
            edu.iris.Fissures.AuditInfo[] _ob_a2 = edu.iris.Fissures.AuditInfoOptHelper.read(in);
            add_locators(_ob_a0, _ob_a1, _ob_a2);
            out = handler.createReply();
        }
        catch(OriginNotFound _ob_ex)
        {
            out = handler.createExceptionReply();
            OriginNotFoundHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_add_magnitude(org.omg.CORBA.portable.InputStream in,
                         org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            String _ob_a0 = OriginIdHelper.read(in);
            Magnitude _ob_a1 = MagnitudeHelper.read(in);
            edu.iris.Fissures.AuditInfo[] _ob_a2 = edu.iris.Fissures.AuditInfoOptHelper.read(in);
            add_magnitude(_ob_a0, _ob_a1, _ob_a2);
            out = handler.createReply();
        }
        catch(OriginNotFound _ob_ex)
        {
            out = handler.createExceptionReply();
            OriginNotFoundHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_add_origin(org.omg.CORBA.portable.InputStream in,
                      org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        edu.iris.Fissures.Time _ob_a0 = edu.iris.Fissures.TimeHelper.read(in);
        edu.iris.Fissures.Location _ob_a1 = edu.iris.Fissures.LocationHelper.read(in);
        Magnitude[] _ob_a2 = MagnitudeSeqHelper.read(in);
        Locator[] _ob_a3 = LocatorSeqHelper.read(in);
        boolean _ob_a4 = in.read_boolean();
        String _ob_a5 = CatalogHelper.read(in);
        String _ob_a6 = ContributorHelper.read(in);
        edu.iris.Fissures.AuditInfo[] _ob_a7 = edu.iris.Fissures.AuditInfoOptHelper.read(in);
        String _ob_r = add_origin(_ob_a0, _ob_a1, _ob_a2, _ob_a3, _ob_a4, _ob_a5, _ob_a6, _ob_a7);
        out = handler.createReply();
        OriginIdHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_delete_origin(org.omg.CORBA.portable.InputStream in,
                         org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            String _ob_a0 = OriginIdHelper.read(in);
            edu.iris.Fissures.AuditInfo[] _ob_a1 = edu.iris.Fissures.AuditInfoOptHelper.read(in);
            delete_origin(_ob_a0, _ob_a1);
            out = handler.createReply();
        }
        catch(OriginNotFound _ob_ex)
        {
            out = handler.createExceptionReply();
            OriginNotFoundHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_destroy(org.omg.CORBA.portable.InputStream in,
                   org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        destroy();
        out = handler.createReply();
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_get_attributes(org.omg.CORBA.portable.InputStream in,
                          org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        EventAttr _ob_r = get_attributes();
        out = handler.createReply();
        EventAttrHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_get_audit_trail(org.omg.CORBA.portable.InputStream in,
                           org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            edu.iris.Fissures.AuditElement[] _ob_r = get_audit_trail();
            out = handler.createReply();
            edu.iris.Fissures.AuditTrailHelper.write(out, _ob_r);
        }
        catch(edu.iris.Fissures.NotImplemented _ob_ex)
        {
            out = handler.createExceptionReply();
            edu.iris.Fissures.NotImplementedHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_get_audit_trail_for_origin(org.omg.CORBA.portable.InputStream in,
                                      org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            String _ob_a0 = OriginIdHelper.read(in);
            edu.iris.Fissures.AuditElement[] _ob_r = get_audit_trail_for_origin(_ob_a0);
            out = handler.createReply();
            edu.iris.Fissures.AuditTrailHelper.write(out, _ob_r);
        }
        catch(OriginNotFound _ob_ex)
        {
            out = handler.createExceptionReply();
            OriginNotFoundHelper.write(out, _ob_ex);
        }
        catch(edu.iris.Fissures.NotImplemented _ob_ex)
        {
            out = handler.createExceptionReply();
            edu.iris.Fissures.NotImplementedHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_get_locators(org.omg.CORBA.portable.InputStream in,
                        org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            String _ob_a0 = OriginIdHelper.read(in);
            Locator[] _ob_r = get_locators(_ob_a0);
            out = handler.createReply();
            LocatorSeqHelper.write(out, _ob_r);
        }
        catch(OriginNotFound _ob_ex)
        {
            out = handler.createExceptionReply();
            OriginNotFoundHelper.write(out, _ob_ex);
        }
        catch(edu.iris.Fissures.NotImplemented _ob_ex)
        {
            out = handler.createExceptionReply();
            edu.iris.Fissures.NotImplementedHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_get_origin(org.omg.CORBA.portable.InputStream in,
                      org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            String _ob_a0 = OriginIdHelper.read(in);
            Origin _ob_r = get_origin(_ob_a0);
            out = handler.createReply();
            OriginHelper.write(out, _ob_r);
        }
        catch(OriginNotFound _ob_ex)
        {
            out = handler.createExceptionReply();
            OriginNotFoundHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_get_origins(org.omg.CORBA.portable.InputStream in,
                       org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        Origin[] _ob_r = get_origins();
        out = handler.createReply();
        OriginSeqHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_get_preferred_origin(org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            Origin _ob_r = get_preferred_origin();
            out = handler.createReply();
            OriginHelper.write(out, _ob_r);
        }
        catch(NoPreferredOrigin _ob_ex)
        {
            out = handler.createExceptionReply();
            NoPreferredOriginHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_set_preferred_origin(org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            String _ob_a0 = OriginIdHelper.read(in);
            edu.iris.Fissures.AuditInfo[] _ob_a1 = edu.iris.Fissures.AuditInfoOptHelper.read(in);
            set_preferred_origin(_ob_a0, _ob_a1);
            out = handler.createReply();
        }
        catch(OriginNotFound _ob_ex)
        {
            out = handler.createExceptionReply();
            OriginNotFoundHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_update_region(org.omg.CORBA.portable.InputStream in,
                         org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        edu.iris.Fissures.FlinnEngdahlRegion _ob_a0 = edu.iris.Fissures.FlinnEngdahlRegionHelper.read(in);
        edu.iris.Fissures.AuditInfo[] _ob_a1 = edu.iris.Fissures.AuditInfoOptHelper.read(in);
        update_region(_ob_a0, _ob_a1);
        out = handler.createReply();
        return out;
    }
}
