// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfEvent;

//
// IDL:iris.edu/Fissures/IfEvent/EventAccess:1.0
//
public class EventAccessPOATie extends EventAccessPOA
{
    private EventAccessOperations _ob_delegate_;
    private org.omg.PortableServer.POA _ob_poa_;

    public
    EventAccessPOATie(EventAccessOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public
    EventAccessPOATie(EventAccessOperations delegate, org.omg.PortableServer.POA poa)
    {
        _ob_delegate_ = delegate;
        _ob_poa_ = poa;
    }

    public EventAccessOperations
    _delegate()
    {
        return _ob_delegate_;
    }

    public void
    _delegate(EventAccessOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public org.omg.PortableServer.POA
    _default_POA()
    {
        if(_ob_poa_ != null)
            return _ob_poa_;
        else
            return super._default_POA();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventAccess/a_writeable:1.0
    //
    public Event
    a_writeable()
    {
        return _ob_delegate_.a_writeable();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventAccess/parm_svc:1.0
    //
    public edu.iris.Fissures.IfParameterMgr.ParameterComponent
    parm_svc()
    {
        return _ob_delegate_.parm_svc();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventMgr/a_factory:1.0
    //
    public EventFactory
    a_factory()
    {
        return _ob_delegate_.a_factory();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventDC/a_finder:1.0
    //
    public EventFinder
    a_finder()
    {
        return _ob_delegate_.a_finder();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventDC/a_channel_finder:1.0
    //
    public EventChannelFinder
    a_channel_finder()
    {
        return _ob_delegate_.a_channel_finder();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventAccess/get_attributes:1.0
    //
    public EventAttr
    get_attributes()
    {
        return _ob_delegate_.get_attributes();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventAccess/get_origins:1.0
    //
    public Origin[]
    get_origins()
    {
        return _ob_delegate_.get_origins();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventAccess/get_origin:1.0
    //
    public Origin
    get_origin(String the_origin)
        throws OriginNotFound
    {
        return _ob_delegate_.get_origin(the_origin);
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventAccess/get_preferred_origin:1.0
    //
    public Origin
    get_preferred_origin()
        throws NoPreferredOrigin
    {
        return _ob_delegate_.get_preferred_origin();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventAccess/get_locators:1.0
    //
    public Locator[]
    get_locators(String an_origin)
        throws OriginNotFound,
               edu.iris.Fissures.NotImplemented
    {
        return _ob_delegate_.get_locators(an_origin);
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventAccess/get_audit_trail_for_origin:1.0
    //
    public edu.iris.Fissures.AuditElement[]
    get_audit_trail_for_origin(String the_origin)
        throws OriginNotFound,
               edu.iris.Fissures.NotImplemented
    {
        return _ob_delegate_.get_audit_trail_for_origin(the_origin);
    }

    //
    // IDL:iris.edu/Fissures/AuditSystemAccess/get_audit_trail:1.0
    //
    public edu.iris.Fissures.AuditElement[]
    get_audit_trail()
        throws edu.iris.Fissures.NotImplemented
    {
        return _ob_delegate_.get_audit_trail();
    }
}
