// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfEvent;

//
// IDL:iris.edu/Fissures/IfEvent/EventDC:1.0
//
/**
 * The Event DataCenter Interface. This is the top level interface
 *within IfEvent. It should be the only interface that should be
 *registered with a Naming Service. All other interfaces should
 *be located via methods in this interface.
 **/

public interface EventDC extends EventDCOperations,
                                 org.omg.CORBA.Object,
                                 org.omg.CORBA.portable.IDLEntity
{
}
