// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfService;

//
// IDL:iris.edu/Fissures/IfService/UnknownConfiguration:1.0
//
/***/

final public class UnknownConfiguration extends org.omg.CORBA.UserException
{
    public
    UnknownConfiguration()
    {
        super(UnknownConfigurationHelper.id());
    }

    public
    UnknownConfiguration(String config_id)
    {
        super(UnknownConfigurationHelper.id());
        this.config_id = config_id;
    }

    public
    UnknownConfiguration(String _reason,
                         String config_id)
    {
        super(UnknownConfigurationHelper.id() + " " + _reason);
        this.config_id = config_id;
    }

    public String config_id;
}
