// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfRealTimeCollector;

//
// IDL:iris.edu/Fissures/IfRealTimeCollector/RealTimeCollectorSeq:1.0
//
final public class RealTimeCollectorSeqHolder implements org.omg.CORBA.portable.Streamable
{
    public RealTimeCollector[] value;

    public
    RealTimeCollectorSeqHolder()
    {
    }

    public
    RealTimeCollectorSeqHolder(RealTimeCollector[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = RealTimeCollectorSeqHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        RealTimeCollectorSeqHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return RealTimeCollectorSeqHelper.type();
    }
}
