// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfDataSetMgr;

//
// IDL:iris.edu/Fissures/IfDataSetMgr/MotionVectorNode:1.0
//
final public class MotionVectorNodeHolder implements org.omg.CORBA.portable.Streamable
{
    public MotionVectorNode value;

    public
    MotionVectorNodeHolder()
    {
    }

    public
    MotionVectorNodeHolder(MotionVectorNode initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = MotionVectorNodeHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        MotionVectorNodeHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return MotionVectorNodeHelper.type();
    }
}
