// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures;

//
// IDL:iris.edu/Fissures/Area:1.0
//
final public class AreaHolder implements org.omg.CORBA.portable.Streamable
{
    public Area value;

    public
    AreaHolder()
    {
    }

    public
    AreaHolder(Area initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = AreaHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        AreaHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return AreaHelper.type();
    }
}
