// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures;

//
// IDL:iris.edu/Fissures/FissuresException:1.0
//
final public class FissuresExceptionHolder implements org.omg.CORBA.portable.Streamable
{
    public FissuresException value;

    public
    FissuresExceptionHolder()
    {
    }

    public
    FissuresExceptionHolder(FissuresException initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = FissuresExceptionHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        FissuresExceptionHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return FissuresExceptionHelper.type();
    }
}
