// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures;

//
// IDL:iris.edu/Fissures/ML_MAG_TYPE:1.0
//
/***/

public interface ML_MAG_TYPE
{
    String value = "edu.iris.Fissures/MagType/ML";
}
