// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures;

//
// IDL:iris.edu/Fissures/PointDistanceArea:1.0
//
/***/

public abstract class PointDistanceArea implements org.omg.CORBA.portable.StreamableValue,
                                                   Area
{
    //
    // IDL:iris.edu/Fissures/PointDistanceArea/latitude:1.0
    //
    /***/

    public float latitude;

    //
    // IDL:iris.edu/Fissures/PointDistanceArea/longitude:1.0
    //
    /***/

    public float longitude;

    //
    // IDL:iris.edu/Fissures/PointDistanceArea/min_distance:1.0
    //
    /** must be either angular or length */

    public Quantity min_distance;

    //
    // IDL:iris.edu/Fissures/PointDistanceArea/max_distance:1.0
    //
    /** must be either angular or length */

    public Quantity max_distance;

    private static String[] _OB_truncatableIds_ =
    {
        PointDistanceAreaHelper.id()
    };

    public String[]
    _truncatable_ids()
    {
        return _OB_truncatableIds_;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        latitude = in.read_float();
        longitude = in.read_float();
        min_distance = QuantityHelper.read(in);
        max_distance = QuantityHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        out.write_float(latitude);
        out.write_float(longitude);
        QuantityHelper.write(out, min_distance);
        QuantityHelper.write(out, max_distance);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return PointDistanceAreaHelper.type();
    }
}
