// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfSeismogramDC;

//
// IDL:iris.edu/Fissures/IfSeismogramDC/LocalMotionVector:1.0
//
final public class LocalMotionVectorHolder implements org.omg.CORBA.portable.Streamable
{
    public LocalMotionVector value;

    public
    LocalMotionVectorHolder()
    {
    }

    public
    LocalMotionVectorHolder(LocalMotionVector initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = LocalMotionVectorHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        LocalMotionVectorHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return LocalMotionVectorHelper.type();
    }
}
