// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfSeismogramMgr;

//
// IDL:iris.edu/Fissures/IfSeismogramMgr/ChannelMirrorAdmin:1.0
//
/**
 * ChannelMirrorAdmin - provides a means to administer the mirroring
 * functionality of this seismogram manager.
 **/

public interface ChannelMirrorAdminOperations
{
    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/ChannelMirrorAdmin/active_seismogram_mirrors:1.0
    //
    /** Determine the number of active mirror registrations */

    int
    active_seismogram_mirrors();

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/ChannelMirrorAdmin/get_mirrored_seismograms:1.0
    //
    /** Retrieve the Seismograms that are being mirrored to a remote
     *server */

    Seismogram[]
    get_mirrored_seismograms();

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/ChannelMirrorAdmin/get_factory_mirrors:1.0
    //
    /** Retrieve the SeismogramFactories registered to be mirrored */

    SeismogramFactory[]
    get_factory_mirrors();

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/ChannelMirrorAdmin/stop_mirrors:1.0
    //
    /** Stop mirroring to the specified mirrors */

    void
    stop_mirrors(SeismogramFactory[] mirrors);

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/ChannelMirrorAdmin/stop_mirroring:1.0
    //
    /** Stop all the mirroring process */

    void
    stop_mirroring();

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/ChannelMirrorAdmin/resume_mirroring:1.0
    //
    /** Restart the process to mirrot seismograms */

    void
    resume_mirroring();

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/ChannelMirrorAdmin/is_mirroring:1.0
    //
    /** Is the service current mirroring */

    boolean
    is_mirroring();
}
