// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfSeismogramMgr;

//
// IDL:iris.edu/Fissures/IfSeismogramMgr/ChannelMirrorRegistry:1.0
//
public class ChannelMirrorRegistryPOATie extends ChannelMirrorRegistryPOA
{
    private ChannelMirrorRegistryOperations _ob_delegate_;
    private org.omg.PortableServer.POA _ob_poa_;

    public
    ChannelMirrorRegistryPOATie(ChannelMirrorRegistryOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public
    ChannelMirrorRegistryPOATie(ChannelMirrorRegistryOperations delegate, org.omg.PortableServer.POA poa)
    {
        _ob_delegate_ = delegate;
        _ob_poa_ = poa;
    }

    public ChannelMirrorRegistryOperations
    _delegate()
    {
        return _ob_delegate_;
    }

    public void
    _delegate(ChannelMirrorRegistryOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public org.omg.PortableServer.POA
    _default_POA()
    {
        if(_ob_poa_ != null)
            return _ob_poa_;
        else
            return super._default_POA();
    }

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/ChannelMirrorRegistry/register:1.0
    //
    public String
    register(MirrorFactory a_mirror,
             edu.iris.Fissures.IfNetwork.ChannelId[] filter)
        throws UnknownChannel,
               NotMirroring
    {
        return _ob_delegate_.register(a_mirror,
                                      filter);
    }

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/ChannelMirrorRegistry/unregister:1.0
    //
    public void
    unregister(String a_mirror)
        throws UnknownMirrorId
    {
        _ob_delegate_.unregister(a_mirror);
    }

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/ChannelMirrorRegistry/get_mirrorable_channels:1.0
    //
    public edu.iris.Fissures.IfNetwork.ChannelId[]
    get_mirrorable_channels()
    {
        return _ob_delegate_.get_mirrorable_channels();
    }
}
