// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfDataSetMgr;

//
// IDL:iris.edu/Fissures/IfDataSetMgr/LocalDataSet:1.0
//
final public class LocalDataSetHolder implements org.omg.CORBA.portable.Streamable
{
    public LocalDataSet value;

    public
    LocalDataSetHolder()
    {
    }

    public
    LocalDataSetHolder(LocalDataSet initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = LocalDataSetHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        LocalDataSetHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return LocalDataSetHelper.type();
    }
}
