// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfNetwork;

//
// IDL:iris.edu/Fissures/IfNetwork/Network:1.0
//
public class _NetworkStub extends org.omg.CORBA.portable.ObjectImpl
                          implements Network
{
    private static final String[] _ob_ids_ =
    {
        "IDL:iris.edu/Fissures/IfNetwork/Network:1.0",
    };

    public String[]
    _ids()
    {
        return _ob_ids_;
    }

    final public static java.lang.Class _ob_opsClass = Network.class;
}
