// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfNetwork;

//
// IDL:iris.edu/Fissures/IfNetwork/ChannelGroupIter:1.0
//
public class ChannelGroupIterPOATie extends ChannelGroupIterPOA
{
    private ChannelGroupIterOperations _ob_delegate_;
    private org.omg.PortableServer.POA _ob_poa_;

    public
    ChannelGroupIterPOATie(ChannelGroupIterOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public
    ChannelGroupIterPOATie(ChannelGroupIterOperations delegate, org.omg.PortableServer.POA poa)
    {
        _ob_delegate_ = delegate;
        _ob_poa_ = poa;
    }

    public ChannelGroupIterOperations
    _delegate()
    {
        return _ob_delegate_;
    }

    public void
    _delegate(ChannelGroupIterOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public org.omg.PortableServer.POA
    _default_POA()
    {
        if(_ob_poa_ != null)
            return _ob_poa_;
        else
            return super._default_POA();
    }

    //
    // IDL:iris.edu/Fissures/IfNetwork/ChannelGroupIter/how_many_remain:1.0
    //
    public int
    how_many_remain()
    {
        return _ob_delegate_.how_many_remain();
    }

    //
    // IDL:iris.edu/Fissures/IfNetwork/ChannelGroupIter/next_n:1.0
    //
    public boolean
    next_n(int how_many,
           ChannelGroupSeqHolder seq)
    {
        return _ob_delegate_.next_n(how_many,
                                    seq);
    }

    //
    // IDL:iris.edu/Fissures/IfNetwork/ChannelGroupIter/destroy:1.0
    //
    public void
    destroy()
    {
        _ob_delegate_.destroy();
    }
}
