// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfNetwork;

//
// IDL:iris.edu/Fissures/IfNetwork/ConcreteNetworkAccess:1.0
//
final public class ConcreteNetworkAccessHolder implements org.omg.CORBA.portable.Streamable
{
    public ConcreteNetworkAccess value;

    public
    ConcreteNetworkAccessHolder()
    {
    }

    public
    ConcreteNetworkAccessHolder(ConcreteNetworkAccess initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = ConcreteNetworkAccessHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        ConcreteNetworkAccessHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return ConcreteNetworkAccessHelper.type();
    }
}
