// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfNetwork;

//
// IDL:iris.edu/Fissures/IfNetwork/DuplicateSiteId:1.0
//
final public class DuplicateSiteIdHolder implements org.omg.CORBA.portable.Streamable
{
    public DuplicateSiteId value;

    public
    DuplicateSiteIdHolder()
    {
    }

    public
    DuplicateSiteIdHolder(DuplicateSiteId initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = DuplicateSiteIdHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        DuplicateSiteIdHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return DuplicateSiteIdHelper.type();
    }
}
