// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfNetwork;

//
// IDL:iris.edu/Fissures/IfNetwork/NetworkDC:1.0
//
/**
 * The NetworkDC defines the Network DataCenter
 **/

public interface NetworkDC extends NetworkDCOperations,
                                   org.omg.CORBA.Object,
                                   org.omg.CORBA.portable.IDLEntity
{
}
