// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfNetwork;

//
// IDL:iris.edu/Fissures/IfNetwork/StationId:1.0
//
final public class StationIdHolder implements org.omg.CORBA.portable.Streamable
{
    public StationId value;

    public
    StationIdHolder()
    {
    }

    public
    StationIdHolder(StationId initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = StationIdHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        StationIdHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return StationIdHelper.type();
    }
}
