// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfNetwork;

//
// IDL:iris.edu/Fissures/IfNetwork/VirtualNetwork:1.0
//
final public class VirtualNetworkHolder implements org.omg.CORBA.portable.Streamable
{
    public VirtualNetwork value;

    public
    VirtualNetworkHolder()
    {
    }

    public
    VirtualNetworkHolder(VirtualNetwork initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = VirtualNetworkHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        VirtualNetworkHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return VirtualNetworkHelper.type();
    }
}
