// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfPlottable;

//
// IDL:iris.edu/Fissures/IfPlottable/PlottableDC:1.0
//
public class _PlottableDCStub extends org.omg.CORBA.portable.ObjectImpl
                              implements PlottableDC
{
    private static final String[] _ob_ids_ =
    {
        "IDL:iris.edu/Fissures/IfPlottable/PlottableDC:1.0",
    };

    public String[]
    _ids()
    {
        return _ob_ids_;
    }

    final public static java.lang.Class _ob_opsClass = PlottableDCOperations.class;

    //
    // IDL:iris.edu/Fissures/IfPlottable/PlottableDC/custom_sizes:1.0
    //
    public boolean
    custom_sizes()
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("custom_sizes", true);
                    in = _invoke(out);
                    boolean _ob_r = in.read_boolean();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("custom_sizes", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                PlottableDCOperations _ob_self = (PlottableDCOperations)_ob_so.servant;
                try
                {
                    return _ob_self.custom_sizes();
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:iris.edu/Fissures/IfPlottable/PlottableDC/get_plottable:1.0
    //
    public edu.iris.Fissures.Plottable[]
    get_plottable(edu.iris.Fissures.IfSeismogramDC.RequestFilter _ob_a0,
                  edu.iris.Fissures.Dimension _ob_a1)
        throws PlottableNotAvailable,
               UnsupportedDimension,
               edu.iris.Fissures.NotImplemented
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_plottable", true);
                    edu.iris.Fissures.IfSeismogramDC.RequestFilterHelper.write(out, _ob_a0);
                    edu.iris.Fissures.DimensionHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    edu.iris.Fissures.Plottable[] _ob_r = edu.iris.Fissures.PlottableSeqHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(PlottableNotAvailableHelper.id()))
                        throw PlottableNotAvailableHelper.read(in);
                    if(_ob_id.equals(UnsupportedDimensionHelper.id()))
                        throw UnsupportedDimensionHelper.read(in);
                    if(_ob_id.equals(edu.iris.Fissures.NotImplementedHelper.id()))
                        throw edu.iris.Fissures.NotImplementedHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_plottable", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                PlottableDCOperations _ob_self = (PlottableDCOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_plottable(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:iris.edu/Fissures/IfPlottable/PlottableDC/get_whole_day_sizes:1.0
    //
    public edu.iris.Fissures.Dimension[]
    get_whole_day_sizes()
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_whole_day_sizes", true);
                    in = _invoke(out);
                    edu.iris.Fissures.Dimension[] _ob_r = edu.iris.Fissures.DimensionSeqHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_whole_day_sizes", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                PlottableDCOperations _ob_self = (PlottableDCOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_whole_day_sizes();
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:iris.edu/Fissures/IfPlottable/PlottableDC/get_for_day:1.0
    //
    public edu.iris.Fissures.Plottable[]
    get_for_day(edu.iris.Fissures.IfNetwork.ChannelId _ob_a0,
                int _ob_a1,
                int _ob_a2,
                edu.iris.Fissures.Dimension _ob_a3)
        throws PlottableNotAvailable,
               UnsupportedDimension
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_for_day", true);
                    edu.iris.Fissures.IfNetwork.ChannelIdHelper.write(out, _ob_a0);
                    out.write_long(_ob_a1);
                    out.write_long(_ob_a2);
                    edu.iris.Fissures.DimensionHelper.write(out, _ob_a3);
                    in = _invoke(out);
                    edu.iris.Fissures.Plottable[] _ob_r = edu.iris.Fissures.PlottableSeqHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(PlottableNotAvailableHelper.id()))
                        throw PlottableNotAvailableHelper.read(in);
                    if(_ob_id.equals(UnsupportedDimensionHelper.id()))
                        throw UnsupportedDimensionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_for_day", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                PlottableDCOperations _ob_self = (PlottableDCOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_for_day(_ob_a0, _ob_a1, _ob_a2, _ob_a3);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:iris.edu/Fissures/IfPlottable/PlottableDC/get_event_sizes:1.0
    //
    public edu.iris.Fissures.Dimension[]
    get_event_sizes()
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_event_sizes", true);
                    in = _invoke(out);
                    edu.iris.Fissures.Dimension[] _ob_r = edu.iris.Fissures.DimensionSeqHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_event_sizes", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                PlottableDCOperations _ob_self = (PlottableDCOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_event_sizes();
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:iris.edu/Fissures/IfPlottable/PlottableDC/get_for_event:1.0
    //
    public edu.iris.Fissures.Plottable[]
    get_for_event(edu.iris.Fissures.IfEvent.EventAccess _ob_a0,
                  edu.iris.Fissures.IfNetwork.ChannelId _ob_a1,
                  edu.iris.Fissures.Dimension _ob_a2)
        throws PlottableNotAvailable,
               UnsupportedDimension
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("get_for_event", true);
                    edu.iris.Fissures.IfEvent.EventAccessHelper.write(out, _ob_a0);
                    edu.iris.Fissures.IfNetwork.ChannelIdHelper.write(out, _ob_a1);
                    edu.iris.Fissures.DimensionHelper.write(out, _ob_a2);
                    in = _invoke(out);
                    edu.iris.Fissures.Plottable[] _ob_r = edu.iris.Fissures.PlottableSeqHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(PlottableNotAvailableHelper.id()))
                        throw PlottableNotAvailableHelper.read(in);
                    if(_ob_id.equals(UnsupportedDimensionHelper.id()))
                        throw UnsupportedDimensionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("get_for_event", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                PlottableDCOperations _ob_self = (PlottableDCOperations)_ob_so.servant;
                try
                {
                    return _ob_self.get_for_event(_ob_a0, _ob_a1, _ob_a2);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }
}
