// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfTravelTimeCalculator;

//
// IDL:iris.edu/Fissures/IfTravelTimeCalculator/ModelNameSeq:1.0
//
final public class ModelNameSeqHolder implements org.omg.CORBA.portable.Streamable
{
    public String[] value;

    public
    ModelNameSeqHolder()
    {
    }

    public
    ModelNameSeqHolder(String[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = ModelNameSeqHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        ModelNameSeqHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return ModelNameSeqHelper.type();
    }
}
