// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfTravelTimeCalculator;

//
// IDL:iris.edu/Fissures/IfTravelTimeCalculator/TravelTimeCalculator:1.0
//
public class TravelTimeCalculatorPOATie extends TravelTimeCalculatorPOA
{
    private TravelTimeCalculatorOperations _ob_delegate_;
    private org.omg.PortableServer.POA _ob_poa_;

    public
    TravelTimeCalculatorPOATie(TravelTimeCalculatorOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public
    TravelTimeCalculatorPOATie(TravelTimeCalculatorOperations delegate, org.omg.PortableServer.POA poa)
    {
        _ob_delegate_ = delegate;
        _ob_poa_ = poa;
    }

    public TravelTimeCalculatorOperations
    _delegate()
    {
        return _ob_delegate_;
    }

    public void
    _delegate(TravelTimeCalculatorOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public org.omg.PortableServer.POA
    _default_POA()
    {
        if(_ob_poa_ != null)
            return _ob_poa_;
        else
            return super._default_POA();
    }

    //
    // IDL:iris.edu/Fissures/IfTravelTimeCalculator/TravelTimeCalculator/calculate_travel_times:1.0
    //
    public edu.iris.Fissures.IfEvent.PredictedArrival[]
    calculate_travel_times(String config,
                           edu.iris.Fissures.Location event_location,
                           edu.iris.Fissures.Location receiver_location,
                           String model_id,
                           String[] phases_to_calculate,
                           PhaseNameSeqHolder unknown_phases)
    {
        return _ob_delegate_.calculate_travel_times(config,
                                                    event_location,
                                                    receiver_location,
                                                    model_id,
                                                    phases_to_calculate,
                                                    unknown_phases);
    }

    //
    // IDL:iris.edu/Fissures/IfTravelTimeCalculator/TravelTimeCalculator/known_phases:1.0
    //
    public String[]
    known_phases()
    {
        return _ob_delegate_.known_phases();
    }

    //
    // IDL:iris.edu/Fissures/IfTravelTimeCalculator/TravelTimeCalculator/known_models:1.0
    //
    public String[]
    known_models()
    {
        return _ob_delegate_.known_models();
    }

    //
    // IDL:iris.edu/Fissures/IfService/Service/get_configuration_options:1.0
    //
    public edu.iris.Fissures.IfService.ServiceOption[]
    get_configuration_options()
    {
        return _ob_delegate_.get_configuration_options();
    }

    //
    // IDL:iris.edu/Fissures/IfService/Service/get_default_configuration:1.0
    //
    public edu.iris.Fissures.IfService.ServiceSetting[]
    get_default_configuration()
    {
        return _ob_delegate_.get_default_configuration();
    }

    //
    // IDL:iris.edu/Fissures/IfService/Service/get_configuration:1.0
    //
    public edu.iris.Fissures.IfService.ServiceSetting[]
    get_configuration(String config_id)
        throws edu.iris.Fissures.IfService.UnknownConfiguration
    {
        return _ob_delegate_.get_configuration(config_id);
    }

    //
    // IDL:iris.edu/Fissures/IfService/Service/get_setting_for:1.0
    //
    public edu.iris.Fissures.IfService.ServiceSetting
    get_setting_for(String name)
        throws edu.iris.Fissures.IfService.UnknownOption
    {
        return _ob_delegate_.get_setting_for(name);
    }

    //
    // IDL:iris.edu/Fissures/IfService/Service/set_configuration:1.0
    //
    public String
    set_configuration(edu.iris.Fissures.IfService.ServiceSetting[] settings)
        throws edu.iris.Fissures.IfService.UnknownOption,
               edu.iris.Fissures.IfService.InvalidValue
    {
        return _ob_delegate_.set_configuration(settings);
    }

    //
    // IDL:iris.edu/Fissures/IfService/Service/reset_to_default:1.0
    //
    public String
    reset_to_default()
    {
        return _ob_delegate_.reset_to_default();
    }
}
