// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfService;

//
// IDL:iris.edu/Fissures/IfService/ServiceOption:1.0
//
final public class ServiceOptionHelper
{
    public static void
    insert(org.omg.CORBA.Any any, ServiceOption val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static ServiceOption
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[4];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "name";
            members[0].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string);

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "description";
            members[1].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string);

            members[2] = new org.omg.CORBA.StructMember();
            members[2].name = "type";
            members[2].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string);

            members[3] = new org.omg.CORBA.StructMember();
            members[3].name = "allowed_values";
            members[3].type = orb.create_sequence_tc(0, orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string));

            typeCode_ = orb.create_struct_tc(id(), "ServiceOption", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:iris.edu/Fissures/IfService/ServiceOption:1.0";
    }

    public static ServiceOption
    read(org.omg.CORBA.portable.InputStream in)
    {
        ServiceOption _ob_v = new ServiceOption();
        _ob_v.name = in.read_string();
        _ob_v.description = in.read_string();
        _ob_v.type = in.read_string();
        int len0 = in.read_ulong();
        _ob_v.allowed_values = new String[len0];
        for(int i0 = 0 ; i0 < len0 ; i0++)
            _ob_v.allowed_values[i0] = in.read_string();
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, ServiceOption val)
    {
        out.write_string(val.name);
        out.write_string(val.description);
        out.write_string(val.type);
        int len0 = val.allowed_values.length;
        out.write_ulong(len0);
        for(int i0 = 0 ; i0 < len0 ; i0++)
            out.write_string(val.allowed_values[i0]);
    }
}
