// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfService;

//
// IDL:iris.edu/Fissures/IfService/UnknownConfiguration:1.0
//
final public class UnknownConfigurationHolder implements org.omg.CORBA.portable.Streamable
{
    public UnknownConfiguration value;

    public
    UnknownConfigurationHolder()
    {
    }

    public
    UnknownConfigurationHolder(UnknownConfiguration initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = UnknownConfigurationHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        UnknownConfigurationHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return UnknownConfigurationHelper.type();
    }
}
