// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures;

//
// IDL:iris.edu/Fissures/GlobalArea:1.0
//
final public class GlobalAreaHolder implements org.omg.CORBA.portable.Streamable
{
    public GlobalArea value;

    public
    GlobalAreaHolder()
    {
    }

    public
    GlobalAreaHolder(GlobalArea initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = GlobalAreaHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        GlobalAreaHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return GlobalAreaHelper.type();
    }
}
