// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures;

//
// IDL:iris.edu/Fissures/GlobalArea:1.0
//
/** The whole earth. */

public abstract class GlobalArea implements org.omg.CORBA.portable.StreamableValue,
                                            Area
{
    private static String[] _OB_truncatableIds_ =
    {
        GlobalAreaHelper.id()
    };

    public String[]
    _truncatable_ids()
    {
        return _OB_truncatableIds_;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return GlobalAreaHelper.type();
    }
}
