// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures;

//
// IDL:iris.edu/Fissures/Quantity:1.0
//
/** Allows units to be associated with a value. */

public abstract class Quantity implements org.omg.CORBA.portable.StreamableValue
{
    //
    // IDL:iris.edu/Fissures/Quantity/value:1.0
    //
    /***/

    public double value;

    //
    // IDL:iris.edu/Fissures/Quantity/the_units:1.0
    //
    /***/

    public Unit the_units;

    private static String[] _OB_truncatableIds_ =
    {
        QuantityHelper.id()
    };

    public String[]
    _truncatable_ids()
    {
        return _OB_truncatableIds_;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = in.read_double();
        the_units = UnitHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        out.write_double(value);
        UnitHelper.write(out, the_units);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return QuantityHelper.type();
    }
}
