// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures;

//
// IDL:iris.edu/Fissures/TimeRange:1.0
//
final public class TimeRangeHelper
{
    public static void
    insert(org.omg.CORBA.Any any, TimeRange val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static TimeRange
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[2];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "start_time";
            members[0].type = TimeHelper.type();

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "end_time";
            members[1].type = TimeHelper.type();

            typeCode_ = orb.create_struct_tc(id(), "TimeRange", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:iris.edu/Fissures/TimeRange:1.0";
    }

    public static TimeRange
    read(org.omg.CORBA.portable.InputStream in)
    {
        TimeRange _ob_v = new TimeRange();
        _ob_v.start_time = TimeHelper.read(in);
        _ob_v.end_time = TimeHelper.read(in);
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, TimeRange val)
    {
        TimeHelper.write(out, val.start_time);
        TimeHelper.write(out, val.end_time);
    }
}
