// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures;

//
// IDL:iris.edu/Fissures/UnitBase:1.0
//
final public class UnitBaseHelper
{
    public static void
    insert(org.omg.CORBA.Any any, UnitBase val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static UnitBase
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            String[] members = new String[9];
            members[0] = "METER";
            members[1] = "GRAM";
            members[2] = "SECOND";
            members[3] = "AMPERE";
            members[4] = "KELVIN";
            members[5] = "MOLE";
            members[6] = "CANDELA";
            members[7] = "COUNT";
            members[8] = "COMPOSITE";
            typeCode_ = orb.create_enum_tc(id(), "UnitBase", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:iris.edu/Fissures/UnitBase:1.0";
    }

    public static UnitBase
    read(org.omg.CORBA.portable.InputStream in)
    {
        UnitBase _ob_v;
        _ob_v = UnitBase.from_int(in.read_ulong());
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, UnitBase val)
    {
        out.write_ulong(val.value());
    }
}
