// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfPickMgr;

//
// IDL:iris.edu/Fissures/IfPickMgr/PickMgr:1.0
//
/**
 * The Pick manager is the full access interface into the manager.
 **/

public interface PickMgrOperations extends PickDCOperations
{
    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickMgr/add_pick:1.0
    //
    /***/

    void
    add_pick(String seismogram_id,
             Pick a_pick,
             edu.iris.Fissures.AuditInfo[] audit_info)
        throws edu.iris.Fissures.FissuresException;

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickMgr/add_to_pick_group:1.0
    //
    /***/

    void
    add_to_pick_group(String group_id,
                      String a_pick,
                      edu.iris.Fissures.AuditInfo[] audit_info)
        throws UnknownPick,
               UnknownPickGroup;

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickMgr/update_pick:1.0
    //
    /***/

    void
    update_pick(Pick new_pick_data,
                edu.iris.Fissures.AuditInfo[] audit_info)
        throws edu.iris.Fissures.FissuresException;

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickMgr/delete_pick:1.0
    //
    /***/

    void
    delete_pick(String pick_id,
                edu.iris.Fissures.AuditInfo[] audit_info)
        throws edu.iris.Fissures.FissuresException;

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickMgr/remove_pick_from_group:1.0
    //
    /***/

    void
    remove_pick_from_group(String group_id,
                           String pick_id,
                           edu.iris.Fissures.AuditInfo[] audit_info)
        throws edu.iris.Fissures.FissuresException;

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickMgr/remove_pick_group:1.0
    //
    /***/

    void
    remove_pick_group(String group_id,
                      edu.iris.Fissures.AuditInfo[] audit_info)
        throws edu.iris.Fissures.FissuresException;

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickMgr/create_pick_group:1.0
    //
    /***/

    String
    create_pick_group(String group_name,
                      edu.iris.Fissures.AuditInfo[] audit_info);

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickMgr/make_pick_group:1.0
    //
    /***/

    String
    make_pick_group(PickGroup pick_group,
                    edu.iris.Fissures.AuditInfo[] audit_info);

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickMgr/associate_pickgroup_to_dataset:1.0
    //
    /***/

    void
    associate_pickgroup_to_dataset(String dataset,
                                   String group_id,
                                   edu.iris.Fissures.AuditInfo[] audit_info)
        throws edu.iris.Fissures.FissuresException;
}
