// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfPickMgr;

//
// IDL:iris.edu/Fissures/IfPickMgr/PickMgr:1.0
//
final public class PickMgrHolder implements org.omg.CORBA.portable.Streamable
{
    public PickMgr value;

    public
    PickMgrHolder()
    {
    }

    public
    PickMgrHolder(PickMgr initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = PickMgrHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        PickMgrHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return PickMgrHelper.type();
    }
}
