// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfPickMgr;

//
// IDL:iris.edu/Fissures/IfPickMgr/UnknownPickGroup:1.0
//
final public class UnknownPickGroupHolder implements org.omg.CORBA.portable.Streamable
{
    public UnknownPickGroup value;

    public
    UnknownPickGroupHolder()
    {
    }

    public
    UnknownPickGroupHolder(UnknownPickGroup initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = UnknownPickGroupHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        UnknownPickGroupHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return UnknownPickGroupHelper.type();
    }
}
