// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfPickMgr;

//
// IDL:iris.edu/Fissures/IfPickMgr/Pick:1.0
//
final public class PickHolder implements org.omg.CORBA.portable.Streamable
{
    public Pick value;

    public
    PickHolder()
    {
    }

    public
    PickHolder(Pick initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = PickHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        PickHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return PickHelper.type();
    }
}
