// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfPickMgr;

//
// IDL:iris.edu/Fissures/IfPickMgr/PickGroupSeq:1.0
//
final public class PickGroupSeqHelper
{
    public static void
    insert(org.omg.CORBA.Any any, PickGroup[] val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static PickGroup[]
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            typeCode_ = orb.create_alias_tc(id(), "PickGroupSeq", orb.create_sequence_tc(0, PickGroupHelper.type()));
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:iris.edu/Fissures/IfPickMgr/PickGroupSeq:1.0";
    }

    public static PickGroup[]
    read(org.omg.CORBA.portable.InputStream in)
    {
        PickGroup[] _ob_v;
        int len0 = in.read_ulong();
        _ob_v = new PickGroup[len0];
        for(int i0 = 0 ; i0 < len0 ; i0++)
            _ob_v[i0] = PickGroupHelper.read(in);
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, PickGroup[] val)
    {
        int len0 = val.length;
        out.write_ulong(len0);
        for(int i0 = 0 ; i0 < len0 ; i0++)
            PickGroupHelper.write(out, val[i0]);
    }
}
