// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfPickMgr;

//
// IDL:iris.edu/Fissures/IfPickMgr/PickMgr:1.0
//
public class PickMgrPOATie extends PickMgrPOA
{
    private PickMgrOperations _ob_delegate_;
    private org.omg.PortableServer.POA _ob_poa_;

    public
    PickMgrPOATie(PickMgrOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public
    PickMgrPOATie(PickMgrOperations delegate, org.omg.PortableServer.POA poa)
    {
        _ob_delegate_ = delegate;
        _ob_poa_ = poa;
    }

    public PickMgrOperations
    _delegate()
    {
        return _ob_delegate_;
    }

    public void
    _delegate(PickMgrOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public org.omg.PortableServer.POA
    _default_POA()
    {
        if(_ob_poa_ != null)
            return _ob_poa_;
        else
            return super._default_POA();
    }

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickDC/a_writeable:1.0
    //
    public PickMgr
    a_writeable()
    {
        return _ob_delegate_.a_writeable();
    }

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickMgr/add_pick:1.0
    //
    public void
    add_pick(String seismogram_id,
             Pick a_pick,
             edu.iris.Fissures.AuditInfo[] audit_info)
        throws edu.iris.Fissures.FissuresException
    {
        _ob_delegate_.add_pick(seismogram_id,
                               a_pick,
                               audit_info);
    }

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickMgr/add_to_pick_group:1.0
    //
    public void
    add_to_pick_group(String group_id,
                      String a_pick,
                      edu.iris.Fissures.AuditInfo[] audit_info)
        throws UnknownPick,
               UnknownPickGroup
    {
        _ob_delegate_.add_to_pick_group(group_id,
                                        a_pick,
                                        audit_info);
    }

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickMgr/update_pick:1.0
    //
    public void
    update_pick(Pick new_pick_data,
                edu.iris.Fissures.AuditInfo[] audit_info)
        throws edu.iris.Fissures.FissuresException
    {
        _ob_delegate_.update_pick(new_pick_data,
                                  audit_info);
    }

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickMgr/delete_pick:1.0
    //
    public void
    delete_pick(String pick_id,
                edu.iris.Fissures.AuditInfo[] audit_info)
        throws edu.iris.Fissures.FissuresException
    {
        _ob_delegate_.delete_pick(pick_id,
                                  audit_info);
    }

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickMgr/remove_pick_from_group:1.0
    //
    public void
    remove_pick_from_group(String group_id,
                           String pick_id,
                           edu.iris.Fissures.AuditInfo[] audit_info)
        throws edu.iris.Fissures.FissuresException
    {
        _ob_delegate_.remove_pick_from_group(group_id,
                                             pick_id,
                                             audit_info);
    }

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickMgr/remove_pick_group:1.0
    //
    public void
    remove_pick_group(String group_id,
                      edu.iris.Fissures.AuditInfo[] audit_info)
        throws edu.iris.Fissures.FissuresException
    {
        _ob_delegate_.remove_pick_group(group_id,
                                        audit_info);
    }

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickMgr/create_pick_group:1.0
    //
    public String
    create_pick_group(String group_name,
                      edu.iris.Fissures.AuditInfo[] audit_info)
    {
        return _ob_delegate_.create_pick_group(group_name,
                                               audit_info);
    }

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickMgr/make_pick_group:1.0
    //
    public String
    make_pick_group(PickGroup pick_group,
                    edu.iris.Fissures.AuditInfo[] audit_info)
    {
        return _ob_delegate_.make_pick_group(pick_group,
                                             audit_info);
    }

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickMgr/associate_pickgroup_to_dataset:1.0
    //
    public void
    associate_pickgroup_to_dataset(String dataset,
                                   String group_id,
                                   edu.iris.Fissures.AuditInfo[] audit_info)
        throws edu.iris.Fissures.FissuresException
    {
        _ob_delegate_.associate_pickgroup_to_dataset(dataset,
                                                     group_id,
                                                     audit_info);
    }

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickDC/retrieve_picks_for_seismogram:1.0
    //
    public Pick[]
    retrieve_picks_for_seismogram(String seismogram_id)
        throws edu.iris.Fissures.FissuresException
    {
        return _ob_delegate_.retrieve_picks_for_seismogram(seismogram_id);
    }

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickDC/retrieve_picks_for_site:1.0
    //
    public Pick[]
    retrieve_picks_for_site(edu.iris.Fissures.IfNetwork.SiteId site_id,
                            edu.iris.Fissures.TimeRange time_range)
        throws edu.iris.Fissures.FissuresException
    {
        return _ob_delegate_.retrieve_picks_for_site(site_id,
                                                     time_range);
    }

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickDC/retrieve_pick_group:1.0
    //
    public PickGroup[]
    retrieve_pick_group(String group_id)
        throws edu.iris.Fissures.FissuresException
    {
        return _ob_delegate_.retrieve_pick_group(group_id);
    }

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickDC/retrieve_pick_group_by_name:1.0
    //
    public PickGroup[]
    retrieve_pick_group_by_name(String name)
        throws edu.iris.Fissures.FissuresException
    {
        return _ob_delegate_.retrieve_pick_group_by_name(name);
    }

    //
    // IDL:iris.edu/Fissures/IfPickMgr/PickDC/get_pickgroups_for_dataset:1.0
    //
    public PickGroup[]
    get_pickgroups_for_dataset(String dataset)
        throws edu.iris.Fissures.FissuresException
    {
        return _ob_delegate_.get_pickgroups_for_dataset(dataset);
    }
}
