// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfSeismogramMgr;

//
// IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramFactory:1.0
//
public class _SeismogramFactoryStub extends org.omg.CORBA.portable.ObjectImpl
                                    implements SeismogramFactory
{
    private static final String[] _ob_ids_ =
    {
        "IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramFactory:1.0",
    };

    public String[]
    _ids()
    {
        return _ob_ids_;
    }

    final public static java.lang.Class _ob_opsClass = SeismogramFactoryOperations.class;

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramFactory/active_seismogram_count:1.0
    //
    public int
    active_seismogram_count()
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("active_seismogram_count", true);
                    in = _invoke(out);
                    int _ob_r = in.read_long();
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("active_seismogram_count", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                SeismogramFactoryOperations _ob_self = (SeismogramFactoryOperations)_ob_so.servant;
                try
                {
                    return _ob_self.active_seismogram_count();
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramFactory/create:1.0
    //
    public Seismogram
    create(edu.iris.Fissures.IfSeismogramDC.SeismogramAttr _ob_a0,
           edu.iris.Fissures.AuditInfo[] _ob_a1)
        throws edu.iris.Fissures.FissuresException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("create", true);
                    edu.iris.Fissures.IfSeismogramDC.SeismogramAttrHelper.write(out, _ob_a0);
                    edu.iris.Fissures.AuditInfoOptHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    Seismogram _ob_r = SeismogramHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.iris.Fissures.FissuresExceptionHelper.id()))
                        throw edu.iris.Fissures.FissuresExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("create", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                SeismogramFactoryOperations _ob_self = (SeismogramFactoryOperations)_ob_so.servant;
                try
                {
                    org.omg.CORBA.portable.OutputStream _ob_out = _orb().create_output_stream();
                    edu.iris.Fissures.IfSeismogramDC.SeismogramAttrHelper.write(_ob_out, _ob_a0);
                    org.omg.CORBA.portable.InputStream _ob_in = _ob_out.create_input_stream();
                    _ob_a0 = edu.iris.Fissures.IfSeismogramDC.SeismogramAttrHelper.read(_ob_in);
                    return _ob_self.create(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramFactory/create_from_value:1.0
    //
    public Seismogram
    create_from_value(edu.iris.Fissures.IfSeismogramDC.LocalSeismogram _ob_a0,
                      edu.iris.Fissures.AuditInfo[] _ob_a1)
        throws edu.iris.Fissures.FissuresException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("create_from_value", true);
                    edu.iris.Fissures.IfSeismogramDC.LocalSeismogramHelper.write(out, _ob_a0);
                    edu.iris.Fissures.AuditInfoOptHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    Seismogram _ob_r = SeismogramHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.iris.Fissures.FissuresExceptionHelper.id()))
                        throw edu.iris.Fissures.FissuresExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("create_from_value", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                SeismogramFactoryOperations _ob_self = (SeismogramFactoryOperations)_ob_so.servant;
                try
                {
                    org.omg.CORBA.portable.OutputStream _ob_out = _orb().create_output_stream();
                    edu.iris.Fissures.IfSeismogramDC.LocalSeismogramHelper.write(_ob_out, _ob_a0);
                    org.omg.CORBA.portable.InputStream _ob_in = _ob_out.create_input_stream();
                    _ob_a0 = edu.iris.Fissures.IfSeismogramDC.LocalSeismogramHelper.read(_ob_in);
                    return _ob_self.create_from_value(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramFactory/create_from_values:1.0
    //
    public Seismogram[]
    create_from_values(edu.iris.Fissures.IfSeismogramDC.LocalMotionVector _ob_a0,
                       edu.iris.Fissures.AuditInfo[] _ob_a1)
        throws edu.iris.Fissures.FissuresException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("create_from_values", true);
                    edu.iris.Fissures.IfSeismogramDC.LocalMotionVectorHelper.write(out, _ob_a0);
                    edu.iris.Fissures.AuditInfoOptHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    Seismogram[] _ob_r = SeismogramSeqHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.iris.Fissures.FissuresExceptionHelper.id()))
                        throw edu.iris.Fissures.FissuresExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("create_from_values", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                SeismogramFactoryOperations _ob_self = (SeismogramFactoryOperations)_ob_so.servant;
                try
                {
                    org.omg.CORBA.portable.OutputStream _ob_out = _orb().create_output_stream();
                    edu.iris.Fissures.IfSeismogramDC.LocalMotionVectorHelper.write(_ob_out, _ob_a0);
                    org.omg.CORBA.portable.InputStream _ob_in = _ob_out.create_input_stream();
                    _ob_a0 = edu.iris.Fissures.IfSeismogramDC.LocalMotionVectorHelper.read(_ob_in);
                    return _ob_self.create_from_values(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramFactory/create_from_ref:1.0
    //
    public Seismogram
    create_from_ref(Seismogram _ob_a0,
                    edu.iris.Fissures.AuditInfo[] _ob_a1)
        throws edu.iris.Fissures.FissuresException
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("create_from_ref", true);
                    SeismogramHelper.write(out, _ob_a0);
                    edu.iris.Fissures.AuditInfoOptHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    Seismogram _ob_r = SeismogramHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    if(_ob_id.equals(edu.iris.Fissures.FissuresExceptionHelper.id()))
                        throw edu.iris.Fissures.FissuresExceptionHelper.read(in);
                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("create_from_ref", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                SeismogramFactoryOperations _ob_self = (SeismogramFactoryOperations)_ob_so.servant;
                try
                {
                    return _ob_self.create_from_ref(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }
}
