// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfSeismogramMgr;

//
// IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramFinder:1.0
//
public class SeismogramFinderPOATie extends SeismogramFinderPOA
{
    private SeismogramFinderOperations _ob_delegate_;
    private org.omg.PortableServer.POA _ob_poa_;

    public
    SeismogramFinderPOATie(SeismogramFinderOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public
    SeismogramFinderPOATie(SeismogramFinderOperations delegate, org.omg.PortableServer.POA poa)
    {
        _ob_delegate_ = delegate;
        _ob_poa_ = poa;
    }

    public SeismogramFinderOperations
    _delegate()
    {
        return _ob_delegate_;
    }

    public void
    _delegate(SeismogramFinderOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public org.omg.PortableServer.POA
    _default_POA()
    {
        if(_ob_poa_ != null)
            return _ob_poa_;
        else
            return super._default_POA();
    }

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramComponent/a_finder:1.0
    //
    public SeismogramFinder
    a_finder()
    {
        return _ob_delegate_.a_finder();
    }

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramComponent/a_factory:1.0
    //
    public SeismogramFactory
    a_factory()
    {
        return _ob_delegate_.a_factory();
    }

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramFinder/find_seismograms:1.0
    //
    public SeismogramAccess[]
    find_seismograms(edu.iris.Fissures.IfSeismogramDC.RequestFilter[] a_request)
        throws edu.iris.Fissures.FissuresException
    {
        return _ob_delegate_.find_seismograms(a_request);
    }

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramFinder/find_group:1.0
    //
    public RemoteMotionVector
    find_group(edu.iris.Fissures.IfSeismogramDC.GroupRequest[] a_request)
        throws edu.iris.Fissures.FissuresException
    {
        return _ob_delegate_.find_group(a_request);
    }
}
