// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfSeismogramMgr;

//
// IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramComponent:1.0
//
/**
 * The SeismogramComponent interface is the entry point into the
 * Seismogram Manager
 **/

public interface SeismogramComponentOperations
{
    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramComponent/a_finder:1.0
    //
    /***/

    SeismogramFinder
    a_finder();

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramComponent/a_factory:1.0
    //
    /***/

    SeismogramFactory
    a_factory();
}
