// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfSeismogramMgr;

//
// IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramAccess:1.0
//
/**
 * This interface provides read only access to a seismogram
 **/

public interface SeismogramAccessOperations extends SeismogramComponentOperations,
                                                    edu.iris.Fissures.IfTimeSeries.TimeSeriesAccess
{
    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramAccess/a_writeable:1.0
    //
    /***/

    Seismogram
    a_writeable();

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramAccess/parm_svc:1.0
    //
    /** Defines the ParameterMgr where parameters for this DataSet
     *reside */

    edu.iris.Fissures.IfParameterMgr.ParameterComponent
    parm_svc();

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramAccess/get_attributes:1.0
    //
    /***/

    edu.iris.Fissures.IfSeismogramDC.SeismogramAttr
    get_attributes();

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramAccess/get_range_as_longs:1.0
    //
    /***/

    int[]
    get_range_as_longs(edu.iris.Fissures.Quantity time_range)
        throws edu.iris.Fissures.FissuresException;

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramAccess/get_range_as_shorts:1.0
    //
    /***/

    short[]
    get_range_as_shorts(edu.iris.Fissures.Quantity time_range)
        throws edu.iris.Fissures.FissuresException;

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramAccess/get_range_as_floats:1.0
    //
    /***/

    float[]
    get_range_as_floats(edu.iris.Fissures.Quantity time_range)
        throws edu.iris.Fissures.FissuresException;

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramAccess/get_range_as_doubles:1.0
    //
    /***/

    double[]
    get_range_as_doubles(edu.iris.Fissures.Quantity time_range)
        throws edu.iris.Fissures.FissuresException;

    //
    // IDL:iris.edu/Fissures/IfSeismogramMgr/SeismogramAccess/get_range_as_encoded:1.0
    //
    /***/

    edu.iris.Fissures.IfTimeSeries.EncodedData[]
    get_range_as_encoded(edu.iris.Fissures.Quantity time_range)
        throws edu.iris.Fissures.FissuresException;
}
