// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfParameterMgr;

//
// IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgrAccess:1.0
//
public class ParameterMgrAccessPOATie extends ParameterMgrAccessPOA
{
    private ParameterMgrAccessOperations _ob_delegate_;
    private org.omg.PortableServer.POA _ob_poa_;

    public
    ParameterMgrAccessPOATie(ParameterMgrAccessOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public
    ParameterMgrAccessPOATie(ParameterMgrAccessOperations delegate, org.omg.PortableServer.POA poa)
    {
        _ob_delegate_ = delegate;
        _ob_poa_ = poa;
    }

    public ParameterMgrAccessOperations
    _delegate()
    {
        return _ob_delegate_;
    }

    public void
    _delegate(ParameterMgrAccessOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public org.omg.PortableServer.POA
    _default_POA()
    {
        if(_ob_poa_ != null)
            return _ob_poa_;
        else
            return super._default_POA();
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgrAccess/a_writeable:1.0
    //
    public ParameterMgr
    a_writeable()
    {
        return _ob_delegate_.a_writeable();
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterComponent/a_parmset_finder:1.0
    //
    public ParmSetFinder
    a_parmset_finder()
    {
        return _ob_delegate_.a_parmset_finder();
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterComponent/a_parm__mgr:1.0
    //
    public ParameterMgrAccess
    a_parm__mgr()
    {
        return _ob_delegate_.a_parm__mgr();
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgrAccess/get_parm:1.0
    //
    public org.omg.CORBA.Any
    get_parm(String a_id,
             String parm)
        throws edu.iris.Fissures.FissuresException
    {
        return _ob_delegate_.get_parm(a_id,
                                      parm);
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgrAccess/get_parm_names:1.0
    //
    public String[]
    get_parm_names(String a_id,
                   int how_many,
                   ParameterNameIteratorHolder rest)
        throws edu.iris.Fissures.FissuresException
    {
        return _ob_delegate_.get_parm_names(a_id,
                                            how_many,
                                            rest);
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgrAccess/get_parms:1.0
    //
    public Parm[]
    get_parms(String a_id,
              String[] names)
        throws edu.iris.Fissures.FissuresException
    {
        return _ob_delegate_.get_parms(a_id,
                                       names);
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgrAccess/get_all_parms:1.0
    //
    public Parm[]
    get_all_parms(String a_id,
                  int how_many,
                  ParameterIteratorHolder rest)
        throws edu.iris.Fissures.FissuresException
    {
        return _ob_delegate_.get_all_parms(a_id,
                                           how_many,
                                           rest);
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgrAccess/get_parm_set:1.0
    //
    public Parm[]
    get_parm_set(String a_id,
                 String parm_def)
        throws edu.iris.Fissures.FissuresException
    {
        return _ob_delegate_.get_parm_set(a_id,
                                          parm_def);
    }
}
