// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfParameterMgr;

//
// IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgrAccess:1.0
//
/**
 * The ParameterMgrAccess provide read capiblity into the manager.
 **/

public interface ParameterMgrAccessOperations extends ParameterComponentOperations
{
    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgrAccess/a_writeable:1.0
    //
    /***/

    ParameterMgr
    a_writeable();

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgrAccess/get_parm:1.0
    //
    /***/

    org.omg.CORBA.Any
    get_parm(String a_id,
             String parm)
        throws edu.iris.Fissures.FissuresException;

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgrAccess/get_parm_names:1.0
    //
    /***/

    String[]
    get_parm_names(String a_id,
                   int how_many,
                   ParameterNameIteratorHolder rest)
        throws edu.iris.Fissures.FissuresException;

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgrAccess/get_parms:1.0
    //
    /***/

    Parm[]
    get_parms(String a_id,
              String[] names)
        throws edu.iris.Fissures.FissuresException;

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgrAccess/get_all_parms:1.0
    //
    /***/

    Parm[]
    get_all_parms(String a_id,
                  int how_many,
                  ParameterIteratorHolder rest)
        throws edu.iris.Fissures.FissuresException;

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgrAccess/get_parm_set:1.0
    //
    /***/

    Parm[]
    get_parm_set(String a_id,
                 String parm_def)
        throws edu.iris.Fissures.FissuresException;
}
