// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfParameterMgr;

//
// IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgr:1.0
//
public abstract class ParameterMgrPOA
    extends org.omg.PortableServer.Servant
    implements org.omg.CORBA.portable.InvokeHandler,
               ParameterMgrOperations
{
    static final String[] _ob_ids_ =
    {
        "IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgr:1.0",
        "IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgrAccess:1.0",
        "IDL:iris.edu/Fissures/IfParameterMgr/ParameterComponent:1.0"
    };

    public ParameterMgr
    _this()
    {
        return ParameterMgrHelper.narrow(super._this_object());
    }

    public ParameterMgr
    _this(org.omg.CORBA.ORB orb)
    {
        return ParameterMgrHelper.narrow(super._this_object(orb));
    }

    public String[]
    _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId)
    {
        return _ob_ids_;
    }

    public org.omg.CORBA.portable.OutputStream
    _invoke(String opName,
            org.omg.CORBA.portable.InputStream in,
            org.omg.CORBA.portable.ResponseHandler handler)
    {
        final String[] _ob_names =
        {
            "_get_a_factory",
            "_get_a_parm__mgr",
            "_get_a_parmset_finder",
            "_get_a_writeable",
            "add_parm",
            "add_parms",
            "create_parm",
            "delete_parm_",
            "delete_parms",
            "get_all_parms",
            "get_parm",
            "get_parm_names",
            "get_parm_set",
            "get_parms",
            "update_parm",
            "update_parms"
        };

        int _ob_left = 0;
        int _ob_right = _ob_names.length;
        int _ob_index = -1;

        while(_ob_left < _ob_right)
        {
            int _ob_m = (_ob_left + _ob_right) / 2;
            int _ob_res = _ob_names[_ob_m].compareTo(opName);
            if(_ob_res == 0)
            {
                _ob_index = _ob_m;
                break;
            }
            else if(_ob_res > 0)
                _ob_right = _ob_m;
            else
                _ob_left = _ob_m + 1;
        }

        switch(_ob_index)
        {
        case 0: // _get_a_factory
            return _OB_att_get_a_factory(in, handler);

        case 1: // _get_a_parm__mgr
            return _OB_att_get_a_parm__mgr(in, handler);

        case 2: // _get_a_parmset_finder
            return _OB_att_get_a_parmset_finder(in, handler);

        case 3: // _get_a_writeable
            return _OB_att_get_a_writeable(in, handler);

        case 4: // add_parm
            return _OB_op_add_parm(in, handler);

        case 5: // add_parms
            return _OB_op_add_parms(in, handler);

        case 6: // create_parm
            return _OB_op_create_parm(in, handler);

        case 7: // delete_parm_
            return _OB_op_delete_parm_(in, handler);

        case 8: // delete_parms
            return _OB_op_delete_parms(in, handler);

        case 9: // get_all_parms
            return _OB_op_get_all_parms(in, handler);

        case 10: // get_parm
            return _OB_op_get_parm(in, handler);

        case 11: // get_parm_names
            return _OB_op_get_parm_names(in, handler);

        case 12: // get_parm_set
            return _OB_op_get_parm_set(in, handler);

        case 13: // get_parms
            return _OB_op_get_parms(in, handler);

        case 14: // update_parm
            return _OB_op_update_parm(in, handler);

        case 15: // update_parms
            return _OB_op_update_parms(in, handler);
        }

        throw new org.omg.CORBA.BAD_OPERATION();
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_att_get_a_factory(org.omg.CORBA.portable.InputStream in,
                          org.omg.CORBA.portable.ResponseHandler handler)
    {
        ParameterFactory _ob_r = a_factory();
        org.omg.CORBA.portable.OutputStream out = handler.createReply();
        ParameterFactoryHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_att_get_a_parm__mgr(org.omg.CORBA.portable.InputStream in,
                            org.omg.CORBA.portable.ResponseHandler handler)
    {
        ParameterMgrAccess _ob_r = a_parm__mgr();
        org.omg.CORBA.portable.OutputStream out = handler.createReply();
        ParameterMgrAccessHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_att_get_a_parmset_finder(org.omg.CORBA.portable.InputStream in,
                                 org.omg.CORBA.portable.ResponseHandler handler)
    {
        ParmSetFinder _ob_r = a_parmset_finder();
        org.omg.CORBA.portable.OutputStream out = handler.createReply();
        ParmSetFinderHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_att_get_a_writeable(org.omg.CORBA.portable.InputStream in,
                            org.omg.CORBA.portable.ResponseHandler handler)
    {
        ParameterMgr _ob_r = a_writeable();
        org.omg.CORBA.portable.OutputStream out = handler.createReply();
        ParameterMgrHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_add_parm(org.omg.CORBA.portable.InputStream in,
                    org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            String _ob_a0 = ParameterIdHelper.read(in);
            Parm _ob_a1 = ParmHelper.read(in);
            add_parm(_ob_a0, _ob_a1);
            out = handler.createReply();
        }
        catch(edu.iris.Fissures.FissuresException _ob_ex)
        {
            out = handler.createExceptionReply();
            edu.iris.Fissures.FissuresExceptionHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_add_parms(org.omg.CORBA.portable.InputStream in,
                     org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            String _ob_a0 = ParameterIdHelper.read(in);
            Parm[] _ob_a1 = ParmSeqHelper.read(in);
            add_parms(_ob_a0, _ob_a1);
            out = handler.createReply();
        }
        catch(edu.iris.Fissures.FissuresException _ob_ex)
        {
            out = handler.createExceptionReply();
            edu.iris.Fissures.FissuresExceptionHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_create_parm(org.omg.CORBA.portable.InputStream in,
                       org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        String _ob_a0 = ParameterIdHelper.read(in);
        ParmDef _ob_a1 = ParmDefHelper.read(in);
        org.omg.CORBA.Any _ob_a2 = in.read_any();
        create_parm(_ob_a0, _ob_a1, _ob_a2);
        out = handler.createReply();
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_delete_parm_(org.omg.CORBA.portable.InputStream in,
                        org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            String _ob_a0 = ParameterIdHelper.read(in);
            Parm _ob_a1 = ParmHelper.read(in);
            delete_parm_(_ob_a0, _ob_a1);
            out = handler.createReply();
        }
        catch(edu.iris.Fissures.FissuresException _ob_ex)
        {
            out = handler.createExceptionReply();
            edu.iris.Fissures.FissuresExceptionHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_delete_parms(org.omg.CORBA.portable.InputStream in,
                        org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            String _ob_a0 = ParameterIdHelper.read(in);
            Parm[] _ob_a1 = ParmSeqHelper.read(in);
            delete_parms(_ob_a0, _ob_a1);
            out = handler.createReply();
        }
        catch(edu.iris.Fissures.FissuresException _ob_ex)
        {
            out = handler.createExceptionReply();
            edu.iris.Fissures.FissuresExceptionHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_get_all_parms(org.omg.CORBA.portable.InputStream in,
                         org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            String _ob_a0 = ParameterIdHelper.read(in);
            int _ob_a1 = in.read_long();
            ParameterIteratorHolder _ob_ah2 = new ParameterIteratorHolder();
            Parm[] _ob_r = get_all_parms(_ob_a0, _ob_a1, _ob_ah2);
            out = handler.createReply();
            ParmSeqHelper.write(out, _ob_r);
            ParameterIteratorHelper.write(out, _ob_ah2.value);
        }
        catch(edu.iris.Fissures.FissuresException _ob_ex)
        {
            out = handler.createExceptionReply();
            edu.iris.Fissures.FissuresExceptionHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_get_parm(org.omg.CORBA.portable.InputStream in,
                    org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            String _ob_a0 = ParameterIdHelper.read(in);
            String _ob_a1 = ParameterNameHelper.read(in);
            org.omg.CORBA.Any _ob_r = get_parm(_ob_a0, _ob_a1);
            out = handler.createReply();
            out.write_any(_ob_r);
        }
        catch(edu.iris.Fissures.FissuresException _ob_ex)
        {
            out = handler.createExceptionReply();
            edu.iris.Fissures.FissuresExceptionHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_get_parm_names(org.omg.CORBA.portable.InputStream in,
                          org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            String _ob_a0 = ParameterIdHelper.read(in);
            int _ob_a1 = in.read_long();
            ParameterNameIteratorHolder _ob_ah2 = new ParameterNameIteratorHolder();
            String[] _ob_r = get_parm_names(_ob_a0, _ob_a1, _ob_ah2);
            out = handler.createReply();
            ParameterNameSeqHelper.write(out, _ob_r);
            ParameterNameIteratorHelper.write(out, _ob_ah2.value);
        }
        catch(edu.iris.Fissures.FissuresException _ob_ex)
        {
            out = handler.createExceptionReply();
            edu.iris.Fissures.FissuresExceptionHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_get_parm_set(org.omg.CORBA.portable.InputStream in,
                        org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            String _ob_a0 = ParameterIdHelper.read(in);
            String _ob_a1 = ParmSetNameHelper.read(in);
            Parm[] _ob_r = get_parm_set(_ob_a0, _ob_a1);
            out = handler.createReply();
            ParmSeqHelper.write(out, _ob_r);
        }
        catch(edu.iris.Fissures.FissuresException _ob_ex)
        {
            out = handler.createExceptionReply();
            edu.iris.Fissures.FissuresExceptionHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_get_parms(org.omg.CORBA.portable.InputStream in,
                     org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            String _ob_a0 = ParameterIdHelper.read(in);
            String[] _ob_a1 = ParameterNameSeqHelper.read(in);
            Parm[] _ob_r = get_parms(_ob_a0, _ob_a1);
            out = handler.createReply();
            ParmSeqHelper.write(out, _ob_r);
        }
        catch(edu.iris.Fissures.FissuresException _ob_ex)
        {
            out = handler.createExceptionReply();
            edu.iris.Fissures.FissuresExceptionHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_update_parm(org.omg.CORBA.portable.InputStream in,
                       org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            String _ob_a0 = ParameterIdHelper.read(in);
            Parm _ob_a1 = ParmHelper.read(in);
            update_parm(_ob_a0, _ob_a1);
            out = handler.createReply();
        }
        catch(edu.iris.Fissures.FissuresException _ob_ex)
        {
            out = handler.createExceptionReply();
            edu.iris.Fissures.FissuresExceptionHelper.write(out, _ob_ex);
        }
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_update_parms(org.omg.CORBA.portable.InputStream in,
                        org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        try
        {
            String _ob_a0 = ParameterIdHelper.read(in);
            Parm[] _ob_a1 = ParmSeqHelper.read(in);
            update_parms(_ob_a0, _ob_a1);
            out = handler.createReply();
        }
        catch(edu.iris.Fissures.FissuresException _ob_ex)
        {
            out = handler.createExceptionReply();
            edu.iris.Fissures.FissuresExceptionHelper.write(out, _ob_ex);
        }
        return out;
    }
}
