// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfParameterMgr;

//
// IDL:iris.edu/Fissures/IfParameterMgr/ParmSetAttr:1.0
//
final public class ParmSetAttrHolder implements org.omg.CORBA.portable.Streamable
{
    public ParmSetAttr value;

    public
    ParmSetAttrHolder()
    {
    }

    public
    ParmSetAttrHolder(ParmSetAttr initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = ParmSetAttrHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        ParmSetAttrHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return ParmSetAttrHelper.type();
    }
}
