// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfParameterMgr;

//
// IDL:iris.edu/Fissures/IfParameterMgr/ParmSet:1.0
//
public class ParmSetPOATie extends ParmSetPOA
{
    private ParmSetOperations _ob_delegate_;
    private org.omg.PortableServer.POA _ob_poa_;

    public
    ParmSetPOATie(ParmSetOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public
    ParmSetPOATie(ParmSetOperations delegate, org.omg.PortableServer.POA poa)
    {
        _ob_delegate_ = delegate;
        _ob_poa_ = poa;
    }

    public ParmSetOperations
    _delegate()
    {
        return _ob_delegate_;
    }

    public void
    _delegate(ParmSetOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public org.omg.PortableServer.POA
    _default_POA()
    {
        if(_ob_poa_ != null)
            return _ob_poa_;
        else
            return super._default_POA();
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParmSetAccess/a_writable:1.0
    //
    public ParmSet
    a_writable()
    {
        return _ob_delegate_.a_writable();
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterComponent/a_parmset_finder:1.0
    //
    public ParmSetFinder
    a_parmset_finder()
    {
        return _ob_delegate_.a_parmset_finder();
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterComponent/a_parm__mgr:1.0
    //
    public ParameterMgrAccess
    a_parm__mgr()
    {
        return _ob_delegate_.a_parm__mgr();
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParmSet/update_name:1.0
    //
    public void
    update_name(String name)
        throws edu.iris.Fissures.FissuresException
    {
        _ob_delegate_.update_name(name);
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParmSet/update_description:1.0
    //
    public void
    update_description(String description)
        throws edu.iris.Fissures.FissuresException
    {
        _ob_delegate_.update_description(description);
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParmSet/add_new_parm_def:1.0
    //
    public void
    add_new_parm_def(ParmDef parm_def)
    {
        _ob_delegate_.add_new_parm_def(parm_def);
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParmSet/add_existing_parm_def:1.0
    //
    public void
    add_existing_parm_def(String definition)
        throws edu.iris.Fissures.FissuresException
    {
        _ob_delegate_.add_existing_parm_def(definition);
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParmSet/delete_parm_def:1.0
    //
    public void
    delete_parm_def(String definition)
        throws edu.iris.Fissures.FissuresException
    {
        _ob_delegate_.delete_parm_def(definition);
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParmSetAccess/get_attributes:1.0
    //
    public ParmSetAttr
    get_attributes()
    {
        return _ob_delegate_.get_attributes();
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParmSetAccess/get_all_parm_defs:1.0
    //
    public ParmDef[]
    get_all_parm_defs()
    {
        return _ob_delegate_.get_all_parm_defs();
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParmSetAccess/get_parm_def:1.0
    //
    public ParmDef
    get_parm_def(String definition)
        throws edu.iris.Fissures.FissuresException
    {
        return _ob_delegate_.get_parm_def(definition);
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParmSetAccess/get_parm_defs:1.0
    //
    public ParmDef[]
    get_parm_defs(String[] definitions)
        throws edu.iris.Fissures.FissuresException
    {
        return _ob_delegate_.get_parm_defs(definitions);
    }
}
