// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfParameterMgr;

//
// IDL:iris.edu/Fissures/IfParameterMgr/Parm:1.0
//
final public class ParmHolder implements org.omg.CORBA.portable.Streamable
{
    public Parm value;

    public
    ParmHolder()
    {
    }

    public
    ParmHolder(Parm initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = ParmHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        ParmHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return ParmHelper.type();
    }
}
