// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfParameterMgr;

//
// IDL:iris.edu/Fissures/IfParameterMgr/ParmSetFinder:1.0
//
/**
 * The ParmSetFinder provides the ability to find a ParmSet. A
 * ParmSet is a user defined collection of parameters.
 **/

public interface ParmSetFinder extends ParmSetFinderOperations,
                                       ParameterComponent,
                                       org.omg.CORBA.portable.IDLEntity
{
}
