// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfParameterMgr;

//
// IDL:iris.edu/Fissures/IfParameterMgr/ParmDef:1.0
//
/***/

final public class ParmDef implements org.omg.CORBA.portable.IDLEntity
{
    public
    ParmDef()
    {
    }

    public
    ParmDef(String parm_name,
            String description,
            String creator)
    {
        this.parm_name = parm_name;
        this.description = description;
        this.creator = creator;
    }

    public String parm_name;
    public String description;
    public String creator;
}
