// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfPlottable;

//
// IDL:iris.edu/Fissures/IfPlottable/UnsupportedDimension:1.0
//
/** The plottable is not available because the server does not support
 *custom dimensions and this is not one of the dimensions it caches.
 **/

final public class UnsupportedDimension extends org.omg.CORBA.UserException
{
    public
    UnsupportedDimension()
    {
        super(UnsupportedDimensionHelper.id());
    }

    public
    UnsupportedDimension(String _reason)
    {
        super(UnsupportedDimensionHelper.id() + " " + _reason);
    }
}
