// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfFilter;

//
// IDL:iris.edu/Fissures/IfFilter/FilterStyle:1.0
//
final public class FilterStyleHelper
{
    public static void
    insert(org.omg.CORBA.Any any, FilterStyle val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static FilterStyle
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[5];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "selection";
            members[0].type = CroppingHelper.type();

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "formula";
            members[1].type = AlgorithmHelper.type();

            members[2] = new org.omg.CORBA.StructMember();
            members[2].name = "two_way";
            members[2].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_boolean);

            members[3] = new org.omg.CORBA.StructMember();
            members[3].name = "corner_freqs";
            members[3].type = FloatSeqHelper.type();

            members[4] = new org.omg.CORBA.StructMember();
            members[4].name = "nPoles";
            members[4].type = ShortSeqHelper.type();

            typeCode_ = orb.create_struct_tc(id(), "FilterStyle", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:iris.edu/Fissures/IfFilter/FilterStyle:1.0";
    }

    public static FilterStyle
    read(org.omg.CORBA.portable.InputStream in)
    {
        FilterStyle _ob_v = new FilterStyle();
        _ob_v.selection = CroppingHelper.read(in);
        _ob_v.formula = AlgorithmHelper.read(in);
        _ob_v.two_way = in.read_boolean();
        _ob_v.corner_freqs = FloatSeqHelper.read(in);
        _ob_v.nPoles = ShortSeqHelper.read(in);
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, FilterStyle val)
    {
        CroppingHelper.write(out, val.selection);
        AlgorithmHelper.write(out, val.formula);
        out.write_boolean(val.two_way);
        FloatSeqHelper.write(out, val.corner_freqs);
        ShortSeqHelper.write(out, val.nPoles);
    }
}
