// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfFilter;

//
// IDL:iris.edu/Fissures/IfFilter/FilterInfo:1.0
//
/***/

final public class FilterInfo implements org.omg.CORBA.portable.IDLEntity
{
    public
    FilterInfo()
    {
    }

    public
    FilterInfo(String[] supported_algorithms,
               Cropping[] supported_croppings,
               boolean supports_two_way)
    {
        this.supported_algorithms = supported_algorithms;
        this.supported_croppings = supported_croppings;
        this.supports_two_way = supports_two_way;
    }

    public String[] supported_algorithms;
    public Cropping[] supported_croppings;
    public boolean supports_two_way;
}
