// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfSeismogramDC;

//
// IDL:iris.edu/Fissures/IfSeismogramDC/DataCenterCallBack:1.0
//
/**
 * The DataCenterCallBack is the interface through which the
 * data center will respond to client that have made
 * asynchronous request.
 **/

public interface DataCenterCallBackOperations
{
    //
    // IDL:iris.edu/Fissures/IfSeismogramDC/DataCenterCallBack/return_seismograms:1.0
    //
    /***/

    void
    return_seismograms(String the_request,
                       LocalSeismogram[] seismograms);

    //
    // IDL:iris.edu/Fissures/IfSeismogramDC/DataCenterCallBack/return_group:1.0
    //
    /***/

    void
    return_group(String the_request,
                 LocalMotionVector[] seismograms);

    //
    // IDL:iris.edu/Fissures/IfSeismogramDC/DataCenterCallBack/return_error:1.0
    //
    /***/

    void
    return_error(String the_request,
                 edu.iris.Fissures.Error the_error,
                 RequestFilter[] filters);

    //
    // IDL:iris.edu/Fissures/IfSeismogramDC/DataCenterCallBack/finished:1.0
    //
    /***/

    void
    finished(String the_request);

    //
    // IDL:iris.edu/Fissures/IfSeismogramDC/DataCenterCallBack/canceled:1.0
    //
    /***/

    void
    canceled(String the_request);
}
