// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfSeismogramDC;

//
// IDL:iris.edu/Fissures/IfSeismogramDC/Property:1.0
//
/***/

final public class Property implements org.omg.CORBA.portable.IDLEntity
{
    public
    Property()
    {
    }

    public
    Property(String name,
             String value)
    {
        this.name = name;
        this.value = value;
    }

    public String name;
    public String value;
}
