// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfEvent;

//
// IDL:iris.edu/Fissures/IfEvent/EventNotify:1.0
//
/** Structure sent in the Any via EventCannel to notify clients that 
 *either a new event (earthquake) has occured, or that a new origin 
 *has been added to an existing event. */

final public class EventNotify implements org.omg.CORBA.portable.IDLEntity
{
    public
    EventNotify()
    {
    }

    public
    EventNotify(EventAccess the_event,
                Origin new_origin,
                boolean new_event)
    {
        this.the_event = the_event;
        this.new_origin = new_origin;
        this.new_event = new_event;
    }

    public EventAccess the_event;
    public Origin new_origin;
    public boolean new_event;
}
