// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfEvent;

//
// IDL:iris.edu/Fissures/IfEvent/EventSeqIter:1.0
//
/***/

public interface EventSeqIterOperations
{
    //
    // IDL:iris.edu/Fissures/IfEvent/EventSeqIter/how_many_remain:1.0
    //
    /***/

    int
    how_many_remain();

    //
    // IDL:iris.edu/Fissures/IfEvent/EventSeqIter/next_n:1.0
    //
    /***/

    boolean
    next_n(int how_many,
           EventAccessSeqHolder seq);

    //
    // IDL:iris.edu/Fissures/IfEvent/EventSeqIter/destroy:1.0
    //
    /***/

    void
    destroy();
}
