// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfEvent;

//
// IDL:iris.edu/Fissures/IfEvent/EventChannelFinder:1.0
//
public class EventChannelFinderPOATie extends EventChannelFinderPOA
{
    private EventChannelFinderOperations _ob_delegate_;
    private org.omg.PortableServer.POA _ob_poa_;

    public
    EventChannelFinderPOATie(EventChannelFinderOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public
    EventChannelFinderPOATie(EventChannelFinderOperations delegate, org.omg.PortableServer.POA poa)
    {
        _ob_delegate_ = delegate;
        _ob_poa_ = poa;
    }

    public EventChannelFinderOperations
    _delegate()
    {
        return _ob_delegate_;
    }

    public void
    _delegate(EventChannelFinderOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public org.omg.PortableServer.POA
    _default_POA()
    {
        if(_ob_poa_ != null)
            return _ob_poa_;
        else
            return super._default_POA();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventChannelFinder/list_channels:1.0
    //
    public EventChannelDefinition[]
    list_channels()
    {
        return _ob_delegate_.list_channels();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventChannelFinder/retrieve_channel:1.0
    //
    public org.omg.CosEventChannelAdmin.ConsumerAdmin
    retrieve_channel(String id)
        throws NotFound
    {
        return _ob_delegate_.retrieve_channel(id);
    }
}
