// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfEvent;

//
// IDL:iris.edu/Fissures/IfEvent/EventChannelDefinition:1.0
//
/** Defines the types of items that will be sent via a specific
 *EventChannel. This allows clients to decide whether a given 
 *event channel delivers events that meet its needs. */

final public class EventChannelDefinition implements org.omg.CORBA.portable.IDLEntity
{
    public
    EventChannelDefinition()
    {
    }

    public
    EventChannelDefinition(String name,
                           edu.iris.Fissures.Area the_area,
                           edu.iris.Fissures.Quantity min_depth,
                           edu.iris.Fissures.Quantity max_depth,
                           String search_types,
                           float min_magnitude,
                           float max_magnitude,
                           String[] catalogs,
                           String[] contributors)
    {
        this.name = name;
        this.the_area = the_area;
        this.min_depth = min_depth;
        this.max_depth = max_depth;
        this.search_types = search_types;
        this.min_magnitude = min_magnitude;
        this.max_magnitude = max_magnitude;
        this.catalogs = catalogs;
        this.contributors = contributors;
    }

    public String name;
    public edu.iris.Fissures.Area the_area;
    public edu.iris.Fissures.Quantity min_depth;
    public edu.iris.Fissures.Quantity max_depth;
    public String search_types;
    public float min_magnitude;
    public float max_magnitude;
    public String[] catalogs;
    public String[] contributors;
}
