// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfEvent;

//
// IDL:iris.edu/Fissures/IfEvent/Event:1.0
//
public class EventPOATie extends EventPOA
{
    private EventOperations _ob_delegate_;
    private org.omg.PortableServer.POA _ob_poa_;

    public
    EventPOATie(EventOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public
    EventPOATie(EventOperations delegate, org.omg.PortableServer.POA poa)
    {
        _ob_delegate_ = delegate;
        _ob_poa_ = poa;
    }

    public EventOperations
    _delegate()
    {
        return _ob_delegate_;
    }

    public void
    _delegate(EventOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public org.omg.PortableServer.POA
    _default_POA()
    {
        if(_ob_poa_ != null)
            return _ob_poa_;
        else
            return super._default_POA();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventAccess/a_writeable:1.0
    //
    public Event
    a_writeable()
    {
        return _ob_delegate_.a_writeable();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventAccess/parm_svc:1.0
    //
    public edu.iris.Fissures.IfParameterMgr.ParameterComponent
    parm_svc()
    {
        return _ob_delegate_.parm_svc();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventMgr/a_factory:1.0
    //
    public EventFactory
    a_factory()
    {
        return _ob_delegate_.a_factory();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventDC/a_finder:1.0
    //
    public EventFinder
    a_finder()
    {
        return _ob_delegate_.a_finder();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventDC/a_channel_finder:1.0
    //
    public EventChannelFinder
    a_channel_finder()
    {
        return _ob_delegate_.a_channel_finder();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/Event/update_region:1.0
    //
    public void
    update_region(edu.iris.Fissures.FlinnEngdahlRegion region,
                  edu.iris.Fissures.AuditInfo[] audit_info)
    {
        _ob_delegate_.update_region(region,
                                    audit_info);
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/Event/destroy:1.0
    //
    public void
    destroy()
    {
        _ob_delegate_.destroy();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/Event/add_origin:1.0
    //
    public String
    add_origin(edu.iris.Fissures.Time origin_time,
               edu.iris.Fissures.Location the_location,
               Magnitude[] magnitudes,
               Locator[] locators,
               boolean preferred,
               String the_catalog,
               String the_contributor,
               edu.iris.Fissures.AuditInfo[] audit_info)
    {
        return _ob_delegate_.add_origin(origin_time,
                                        the_location,
                                        magnitudes,
                                        locators,
                                        preferred,
                                        the_catalog,
                                        the_contributor,
                                        audit_info);
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/Event/add_locators:1.0
    //
    public void
    add_locators(String the_origin,
                 Locator[] locators,
                 edu.iris.Fissures.AuditInfo[] audit_info)
        throws OriginNotFound
    {
        _ob_delegate_.add_locators(the_origin,
                                   locators,
                                   audit_info);
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/Event/add_magnitude:1.0
    //
    public void
    add_magnitude(String the_origin,
                  Magnitude a_magnitude,
                  edu.iris.Fissures.AuditInfo[] audit_info)
        throws OriginNotFound
    {
        _ob_delegate_.add_magnitude(the_origin,
                                    a_magnitude,
                                    audit_info);
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/Event/delete_origin:1.0
    //
    public void
    delete_origin(String the_origin,
                  edu.iris.Fissures.AuditInfo[] audit_info)
        throws OriginNotFound
    {
        _ob_delegate_.delete_origin(the_origin,
                                    audit_info);
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/Event/set_preferred_origin:1.0
    //
    public void
    set_preferred_origin(String the_origin,
                         edu.iris.Fissures.AuditInfo[] audit_info)
        throws OriginNotFound
    {
        _ob_delegate_.set_preferred_origin(the_origin,
                                           audit_info);
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventAccess/get_attributes:1.0
    //
    public EventAttr
    get_attributes()
    {
        return _ob_delegate_.get_attributes();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventAccess/get_origins:1.0
    //
    public Origin[]
    get_origins()
    {
        return _ob_delegate_.get_origins();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventAccess/get_origin:1.0
    //
    public Origin
    get_origin(String the_origin)
        throws OriginNotFound
    {
        return _ob_delegate_.get_origin(the_origin);
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventAccess/get_preferred_origin:1.0
    //
    public Origin
    get_preferred_origin()
        throws NoPreferredOrigin
    {
        return _ob_delegate_.get_preferred_origin();
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventAccess/get_locators:1.0
    //
    public Locator[]
    get_locators(String an_origin)
        throws OriginNotFound,
               edu.iris.Fissures.NotImplemented
    {
        return _ob_delegate_.get_locators(an_origin);
    }

    //
    // IDL:iris.edu/Fissures/IfEvent/EventAccess/get_audit_trail_for_origin:1.0
    //
    public edu.iris.Fissures.AuditElement[]
    get_audit_trail_for_origin(String the_origin)
        throws OriginNotFound,
               edu.iris.Fissures.NotImplemented
    {
        return _ob_delegate_.get_audit_trail_for_origin(the_origin);
    }

    //
    // IDL:iris.edu/Fissures/AuditSystemAccess/get_audit_trail:1.0
    //
    public edu.iris.Fissures.AuditElement[]
    get_audit_trail()
        throws edu.iris.Fissures.NotImplemented
    {
        return _ob_delegate_.get_audit_trail();
    }
}
