// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfEvent;

//
// IDL:iris.edu/Fissures/IfEvent/EventFactory:1.0
//
public abstract class EventFactoryPOA
    extends org.omg.PortableServer.Servant
    implements org.omg.CORBA.portable.InvokeHandler,
               EventFactoryOperations
{
    static final String[] _ob_ids_ =
    {
        "IDL:iris.edu/Fissures/IfEvent/EventFactory:1.0",
        "IDL:iris.edu/Fissures/IfEvent/EventMgr:1.0",
        "IDL:iris.edu/Fissures/IfEvent/EventDC:1.0"
    };

    public EventFactory
    _this()
    {
        return EventFactoryHelper.narrow(super._this_object());
    }

    public EventFactory
    _this(org.omg.CORBA.ORB orb)
    {
        return EventFactoryHelper.narrow(super._this_object(orb));
    }

    public String[]
    _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId)
    {
        return _ob_ids_;
    }

    public org.omg.CORBA.portable.OutputStream
    _invoke(String opName,
            org.omg.CORBA.portable.InputStream in,
            org.omg.CORBA.portable.ResponseHandler handler)
    {
        final String[] _ob_names =
        {
            "_get_a_channel_finder",
            "_get_a_factory",
            "_get_a_finder",
            "create"
        };

        int _ob_left = 0;
        int _ob_right = _ob_names.length;
        int _ob_index = -1;

        while(_ob_left < _ob_right)
        {
            int _ob_m = (_ob_left + _ob_right) / 2;
            int _ob_res = _ob_names[_ob_m].compareTo(opName);
            if(_ob_res == 0)
            {
                _ob_index = _ob_m;
                break;
            }
            else if(_ob_res > 0)
                _ob_right = _ob_m;
            else
                _ob_left = _ob_m + 1;
        }

        switch(_ob_index)
        {
        case 0: // _get_a_channel_finder
            return _OB_att_get_a_channel_finder(in, handler);

        case 1: // _get_a_factory
            return _OB_att_get_a_factory(in, handler);

        case 2: // _get_a_finder
            return _OB_att_get_a_finder(in, handler);

        case 3: // create
            return _OB_op_create(in, handler);
        }

        throw new org.omg.CORBA.BAD_OPERATION();
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_att_get_a_channel_finder(org.omg.CORBA.portable.InputStream in,
                                 org.omg.CORBA.portable.ResponseHandler handler)
    {
        EventChannelFinder _ob_r = a_channel_finder();
        org.omg.CORBA.portable.OutputStream out = handler.createReply();
        EventChannelFinderHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_att_get_a_factory(org.omg.CORBA.portable.InputStream in,
                          org.omg.CORBA.portable.ResponseHandler handler)
    {
        EventFactory _ob_r = a_factory();
        org.omg.CORBA.portable.OutputStream out = handler.createReply();
        EventFactoryHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_att_get_a_finder(org.omg.CORBA.portable.InputStream in,
                         org.omg.CORBA.portable.ResponseHandler handler)
    {
        EventFinder _ob_r = a_finder();
        org.omg.CORBA.portable.OutputStream out = handler.createReply();
        EventFinderHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_create(org.omg.CORBA.portable.InputStream in,
                  org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        EventAttr _ob_a0 = EventAttrHelper.read(in);
        edu.iris.Fissures.AuditInfo[] _ob_a1 = edu.iris.Fissures.AuditInfoOptHelper.read(in);
        Event _ob_r = create(_ob_a0, _ob_a1);
        out = handler.createReply();
        EventHelper.write(out, _ob_r);
        return out;
    }
}
