// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfEvent;

//
// IDL:iris.edu/Fissures/IfEvent/Locator:1.0
//
final public class LocatorHolder implements org.omg.CORBA.portable.Streamable
{
    public Locator value;

    public
    LocatorHolder()
    {
    }

    public
    LocatorHolder(Locator initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = LocatorHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        LocatorHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return LocatorHelper.type();
    }
}
