// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfEvent;

//
// IDL:iris.edu/Fissures/IfEvent/PredictedArrivalSeq:1.0
//
final public class PredictedArrivalSeqHolder implements org.omg.CORBA.portable.Streamable
{
    public PredictedArrival[] value;

    public
    PredictedArrivalSeqHolder()
    {
    }

    public
    PredictedArrivalSeqHolder(PredictedArrival[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = PredictedArrivalSeqHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        PredictedArrivalSeqHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return PredictedArrivalSeqHelper.type();
    }
}
