// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfParameterMgr;

//
// IDL:iris.edu/Fissures/IfParameterMgr/ParameterNameIterator:1.0
//
public class ParameterNameIteratorPOATie extends ParameterNameIteratorPOA
{
    private ParameterNameIteratorOperations _ob_delegate_;
    private org.omg.PortableServer.POA _ob_poa_;

    public
    ParameterNameIteratorPOATie(ParameterNameIteratorOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public
    ParameterNameIteratorPOATie(ParameterNameIteratorOperations delegate, org.omg.PortableServer.POA poa)
    {
        _ob_delegate_ = delegate;
        _ob_poa_ = poa;
    }

    public ParameterNameIteratorOperations
    _delegate()
    {
        return _ob_delegate_;
    }

    public void
    _delegate(ParameterNameIteratorOperations delegate)
    {
        _ob_delegate_ = delegate;
    }

    public org.omg.PortableServer.POA
    _default_POA()
    {
        if(_ob_poa_ != null)
            return _ob_poa_;
        else
            return super._default_POA();
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterNameIterator/next_one:1.0
    //
    public boolean
    next_one(org.omg.CORBA.StringHolder name)
    {
        return _ob_delegate_.next_one(name);
    }

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterNameIterator/next_n:1.0
    //
    public boolean
    next_n(int how_many,
           ParameterNameSeqHolder names)
    {
        return _ob_delegate_.next_n(how_many,
                                    names);
    }

    //
    // IDL:iris.edu/Fissures/FissuresIterator/how_many:1.0
    //
    public int
    how_many()
    {
        return _ob_delegate_.how_many();
    }

    //
    // IDL:iris.edu/Fissures/FissuresIterator/reset:1.0
    //
    public void
    reset()
    {
        _ob_delegate_.reset();
    }

    //
    // IDL:iris.edu/Fissures/FissuresIterator/destroy:1.0
    //
    public void
    destroy()
    {
        _ob_delegate_.destroy();
    }
}
