// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfParameterMgr;

//
// IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgr:1.0
//
/**
 * The ParameterMgr provides full access to the manager.
 **/

public interface ParameterMgrOperations extends ParameterMgrAccessOperations
{
    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgr/a_factory:1.0
    //
    /***/

    ParameterFactory
    a_factory();

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgr/add_parm:1.0
    //
    /***/

    void
    add_parm(String a_id,
             Parm parameter)
        throws edu.iris.Fissures.FissuresException;

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgr/add_parms:1.0
    //
    /***/

    void
    add_parms(String a_id,
              Parm[] parameters)
        throws edu.iris.Fissures.FissuresException;

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgr/create_parm:1.0
    //
    /***/

    void
    create_parm(String a_id,
                ParmDef parm_def,
                org.omg.CORBA.Any value);

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgr/update_parm:1.0
    //
    /***/

    void
    update_parm(String a_id,
                Parm parameter)
        throws edu.iris.Fissures.FissuresException;

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgr/update_parms:1.0
    //
    /***/

    void
    update_parms(String a_id,
                 Parm[] parameters)
        throws edu.iris.Fissures.FissuresException;

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgr/delete_parm_:1.0
    //
    /***/

    void
    delete_parm_(String a_id,
                 Parm parameter)
        throws edu.iris.Fissures.FissuresException;

    //
    // IDL:iris.edu/Fissures/IfParameterMgr/ParameterMgr/delete_parms:1.0
    //
    /***/

    void
    delete_parms(String a_id,
                 Parm[] parameters)
        throws edu.iris.Fissures.FissuresException;
}
