// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfNetwork;

//
// IDL:iris.edu/Fissures/IfNetwork/NetworkFactory:1.0
//
/**
 * The NetworkFactory
 **/

public interface NetworkFactoryOperations
{
    //
    // IDL:iris.edu/Fissures/IfNetwork/NetworkFactory/create:1.0
    //
    /***/

    Network
    create(NetworkAttr my_attributes,
           edu.iris.Fissures.Time start_time,
           edu.iris.Fissures.AuditInfo[] audit_info)
        throws edu.iris.Fissures.FissuresException;

    //
    // IDL:iris.edu/Fissures/IfNetwork/NetworkFactory/create_virtual:1.0
    //
    /***/

    Network
    create_virtual(String name,
                   edu.iris.Fissures.AuditInfo[] audit_info);
}
