// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2000
// Object Oriented Concepts, Inc.
// Billerica, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.0.5

package edu.iris.Fissures.IfNetwork;

//
// IDL:iris.edu/Fissures/IfNetwork/VirtualNetworkAccess:1.0
//
/**
 * The VirtualNetworkAccess represents temporary networks setup by
 * a user for analysis. Virtual network are setup as groups of
 * channels
 **/

public interface VirtualNetworkAccess extends VirtualNetworkAccessOperations,
                                              org.omg.CORBA.Object,
                                              org.omg.CORBA.portable.IDLEntity
{
}
